const FLOWER_LIST = [
  {jpName:"アイビー / アヤメ", enName:"Ivy", flowerLanguage:"「friendship（友情）」「fidelity（忠実、貞節）」「marriage（結婚）」「wedded love（夫婦愛）」"},
  {jpName:"アイリス", enName:"Iris", flowerLanguage:"「message（伝言、メッセージ）」「hope（希望）」「faith（信頼）」「friendship（友情）」「wisdom（知恵、賢さ）」"},
  {jpName:"アガパンサス", enName:"Agapanthus", flowerLanguage:"「love letter（ラブレター）」"},
  {jpName:"アカンサス", enName:"Acanthus", flowerLanguage:"「art（芸術）」「artifice（技巧）」"},
  {jpName:"アキノキリンソウ", enName:"Goldenrod", flowerLanguage:"「precaution（予防、用心、警戒）」「encouragement（励まし）」"},
  {jpName:"アサガオ", enName:"Morning glory", flowerLanguage:"「love in vain（はかない恋）」「affection（愛情）」"},
  {jpName:"アザミ", enName:"Thistle", flowerLanguage:"「independence（独立）」「nobility of character（人格の高潔さ）」「austerity（厳格）」「misanthropy（人間嫌い）」"},
  {jpName:"アザレア/ツツジ", enName:"Azalea", flowerLanguage:"「temperance（節制、禁酒）」「take care of yourself for me（私のためにお体を大切に）」「fragility（もろさ、はかなさ）」"},
  {jpName:"アジサイ", enName:"Hydrangea", flowerLanguage:"「heartlessness（冷酷）」「boastfulness（高慢）」「You are cold（あなたは冷たい人）」"},
  {jpName:"アスター / エゾギク", enName:"China aster", flowerLanguage:"「variety（多様性、変化）」「fidelity（忠実、貞節）」「I will think of you（私はあなたを想うでしょう）」"},
  {jpName:"アネモネ", enName:"Anemone", flowerLanguage:"「anticipation（期待）」「forsaken（見捨てられる、見放される）」"},
  {jpName:"アマリリス", enName:"Amaryllis", flowerLanguage:"「pride（誇り）」「splendid beauty（輝くばかりの美しさ）」"},
  {jpName:"アリウム", enName:"Allium", flowerLanguage:"「prosperity（繁栄）」「good fortune（幸運）」「humility（謙遜）」"},
  {jpName:"アルストロメリア", enName:"Alstroemeria", flowerLanguage:"「friendship（友情）」「devotion（献身的な愛）」"},
  {jpName:"アルメリア", enName:"Thrift", flowerLanguage:"「sympathy（同情、思いやり、共感）」"},
  {jpName:"アロエ", enName:"Aloe", flowerLanguage:"「bitterness（苦痛）」「grief（悲嘆）」"},
  {jpName:"アンスリウム", enName:"Anthurium", flowerLanguage:"「hospitality（温かいもてなし）」"},
  {jpName:"アンズ", enName:"Apricot blossom", flowerLanguage:"「timid love（臆病な愛）」「doubt（疑い）」「distrust（疑惑）」"},
  {jpName:"イチゴ", enName:"Strawberry", flowerLanguage:"「esteem and love（尊重と愛情）」「perfect goodness（完全なる善）」"},
  {jpName:"イヌサフラン / コルチカム", enName:"Meadow saffron", flowerLanguage:"「My best days are past（私の最良の日々は過ぎ去った）」"},
  {jpName:"イベリス", enName:"Candytuft", flowerLanguage:"「indifference（無関心）」"},
  {jpName:"ウメ", enName:"Plum blossom", flowerLanguage:"「Keep your promise（約束を守る）」「fidelity（忠実）」「beauty and longevity（美と長寿）」"},
  {jpName:"エーデルワイス", enName:"Edelweiss", flowerLanguage:"「noble courage（高潔な勇気）」「daring（大胆不敵）」"},
  {jpName:"エニシダ", enName:"Broom", flowerLanguage:"「humility（謙遜、卑下）」「neatness（清潔）」"},
  {jpName:"エリカ", enName:"Heath", flowerLanguage:"「solitude（孤独）」"},
  {jpName:"オジギソウ", enName:"Sensitive plant", flowerLanguage:"「delicate feelings（繊細な感情）」「sensitiveness（感受性、鋭敏）」"},
  {jpName:"オシロイバナ", enName:"Marvel of Peru", flowerLanguage:"「timidity（臆病）」"},
  {jpName:"オダマキ", enName:"Columbine", flowerLanguage:"「folly（愚か）」"},
  {jpName:"オトギリソウ", enName:"St. John’s wort", flowerLanguage:"「superstition（迷信）」「animosity（敵意）」"},
  {jpName:"オーニソガラム", enName:"Star of Bethlehem", flowerLanguage:"「purity（純粋）」「reconciliation（和解）」「hope（希望）」"},
  {jpName:"オリーブ", enName:"Olive", flowerLanguage:"「peace（平和）」「wisdom（知恵、賢さ）」"},
  {jpName:"オレンジ", enName:"Orange", flowerLanguage:"「purity（純粋）」「Your purity equals your loveliness（あなたの純粋さはあなたの愛らしさと釣り合っている）」"},
  {jpName:"カエデ / モミジ", enName:"Maple", flowerLanguage:"「reserve（蓄え、遠慮）」"},
  {jpName:"カスミソウ", enName:"Baby’s breath", flowerLanguage:"「everlasting love（永遠の愛）」「purity of heart（清らかな心）」「innocence（純潔）」"},
  {jpName:"カタバミ", enName:"Wood sorrel", flowerLanguage:"「joy（喜び）」「maternal tenderness（母のやさしさ）」"},
  {jpName:"カトレア", enName:"Cattleya", flowerLanguage:"「mature charm（成熟した大人の魅力）」"},
  {jpName:"カーネーション", enName:"Carnation", flowerLanguage:"「fascination（魅惑、魅力）」「love（愛情）」「distinction（卓越、名声）」"},
  {jpName:"ガーベラ", enName:"Gerbera", flowerLanguage:"「cheerfulness（上機嫌、元気）」「beauty（美）」"},
  {jpName:"カモミール", enName:"Chamomile", flowerLanguage:"「patience in adversity（逆境に耐える）」「energy in adversity（逆境で生まれる力）」"},
  {jpName:"カラー", enName:"Calla lily", flowerLanguage:"「magnificent beauty（華麗なる美）」「feminine modesty（女性のしとやかさ）」"},
  {jpName:"カランコエ", enName:"Kalanchoe", flowerLanguage:"「popularity（人気、人望）」"},
  {jpName:"カルミア", enName:"Mountain laurel", flowerLanguage:"「ambition（大望、野心）」「treachery（裏切り）」"},
  {jpName:"カンナ", enName:"Canna", flowerLanguage:"「paranoia（妄想）」「suspicion（疑い）」"},
  {jpName:"カンパニュラ", enName:"Canterbury bells", flowerLanguage:"「gratitude（感謝）」「constancy（不変、節操）」"},
  {jpName:"キキョウ", enName:"Balloon flower", flowerLanguage:"「endless love（永遠の愛）」「honesty（正直、誠実）」「the return of a friend is desired（友の帰りを願う）」「obedience（従順）」"},
  {jpName:"キク", enName:"Chrysanthemum", flowerLanguage:"「cheerfulness（上機嫌、元気）」「You’re a wonderful friend（あなたはとても素晴らしい友達）」"},
  {jpName:"キョウチクトウ", enName:"Oleander", flowerLanguage:"「caution（用心）」「beware（注意する、用心する）」"},
  {jpName:"キンギョソウ", enName:"Snapdragon", flowerLanguage:"「graciousness（上品さ、優雅さ）」「deception（ごまかし）」"},
  {jpName:"キンセンカ", enName:"Calendula", flowerLanguage:"「grief（悲嘆）」「despair（絶望）」「sorrow（悲しみ、悲哀）」"},
  {jpName:"クチナシ", enName:"Cape jasmine", flowerLanguage:"「I’m too happy（私はとても幸せです）」「transport of joy（喜びを運ぶ）」"},
  {jpName:"グラジオラス", enName:"Gladiolus", flowerLanguage:"「strength of character（人格的強さ）」「sincerity（誠実）」「preparedness（準備）」「remembrance（記憶）」"},
  {jpName:"クリスマスローズ", enName:"Christmas rose", flowerLanguage:"「relieve my anxiety（私の不安をやわらげて）」"},
  {jpName:"クレマチス", enName:"Clematis", flowerLanguage:"「mental beauty（精神の美）」「ingenuity（創意工夫）」「artifice（策略）」"},
  {jpName:"クロッカス", enName:"Crocus", flowerLanguage:"「youthful gladness（青春の喜び）」「cheerfulness（上機嫌、元気）」"},
  {jpName:"クローバー", enName:"Clover", flowerLanguage:"「think of me（私を思って）」"},
  {jpName:"ケイトウ", enName:"Cockscomb", flowerLanguage:"「foppery（〔男の〕おしゃれ）」「affectation（気取り）」「singularity（風変わり）」"},
  {jpName:"ゲッケイジュ", enName:"Laurel", flowerLanguage:"「glory（栄光）」「victory（勝利）」"},
  {jpName:"コスモス", enName:"Cosmos", flowerLanguage:"「harmony（調和）」「peace（平和）」「modesty（謙虚）」「the joys that love and life can bring（愛や人生がもたらす喜び）」「beautiful（美しい）」"},
  {jpName:"コチョウラン", enName:"Phalaenopsis", flowerLanguage:"「love（愛情）」「beauty（美）」「luxury（高級、豪華さ）」「refinement（上品、優雅）」"},
  {jpName:"ゴボウ", enName:"Burdock", flowerLanguage:"「touch me not（私にさわらないで）」「importunity（しつこくせがむ）」"},
  {jpName:"サイネリア / シネラリア", enName:"Cineraria", flowerLanguage:"「always delightful（いつも愉快）」"},
  {jpName:"サクラ", enName:"Cherry blossom", flowerLanguage:"「spiritual beauty（精神の美）」「a good education（優れた教育）」"},
  {jpName:"ザクロ", enName:"Pomegranate", flowerLanguage:"「mature elegance（円熟した優雅さ）」"},
  {jpName:"サフラン", enName:"Saffron crocus", flowerLanguage:"「mirth（歓喜）」「beware of excess（過度をつつしめ）」「Do not abuse（濫用するな）」"},
  {jpName:"サボテン", enName:"Cactus", flowerLanguage:"「endurance（忍耐）」「ardent love（燃えるような愛）」「grandeur（雄大、偉大）」「warmth（優しさ、暖かさ）」"},
  {jpName:"サルビア", enName:"Sage", flowerLanguage:"「esteem（尊敬、尊重）」「wisdom（知恵、賢さ）」「domestic virtue（家庭の徳）」"},
  {jpName:"サンザシ", enName:"Hawthorn", flowerLanguage:"「hope（希望）」"},
  {jpName:"シオン", enName:"Aster", flowerLanguage:"「patience（忍耐）」「daintiness（優美、繊細）」「symbol of love（愛の象徴）」"},
  {jpName:"ジギタリス", enName:"Foxglove", flowerLanguage:"「insincerity（不誠実）」"},
  {jpName:"シクラメン", enName:"Cyclamen", flowerLanguage:"「timid hope（遠慮がちな期待）」「shyness（内気、はにかみ）」「resignation and good-bye（退職と別れの言葉）」"},
  {jpName:"ジニア", enName:"Zinnia", flowerLanguage:"「thoughts of absent friends（不在の友を思う）」「I mourn your absence（あなたの不在を悲しむ）」"},
  {jpName:"シャクナゲ", enName:"Rhododendron", flowerLanguage:"「danger（危険）」「caution（用心）」「beware（注意する、用心する）」"},
  {jpName:"シャクヤク", enName:"Chinese peony", flowerLanguage:"「bashfulness（恥じらい、はにかみ）」「compassion（思いやり）」"},
  {jpName:"ジャスミン", enName:"Jasmine", flowerLanguage:"「amiability（愛想のよさ）」「You are cheerful and graceful（あなたは朗らかで気品がある）」"},
  {jpName:"ジンチョウゲ", enName:"Daphne odora", flowerLanguage:"「glory（栄光）」「immortality（不死、不滅）」"},
  {jpName:"シンビジウム", enName:"Cymbidium", flowerLanguage:"「magnificence（壮麗）」「gorgeous love（華やかな恋）」"},
  {jpName:"スイカズラ", enName:"Honeysuckle", flowerLanguage:"「bonds of love（愛の絆）」「devotion（献身的な愛）」"},
  {jpName:"スイセン", enName:"Narcissus", flowerLanguage:"「self-love（自己愛）」「egotism（自己中心、うぬぼれ）」「unrequited love（報われぬ恋）」"},
  {jpName:"スイートピー", enName:"Sweet pea", flowerLanguage:"「departure（門出）」「good-bye（別れの言葉）」「delicate pleasure（ほのかな喜び）」「tender memory（優しい思い出）」「blissful pleasure（至福の喜び）」"},
  {jpName:"スイレン", enName:"Water lily", flowerLanguage:"「purity of heart（清らかな心）」"},
  {jpName:"スカビオサ", enName:"Scabiosa", flowerLanguage:"「unfortunate love（不幸な愛）」「I have lost all（私はすべてを失った）」"},
  {jpName:"プラタナス", enName:"Sycamore", flowerLanguage:"「genius（天才）」「curiosity（好奇心）」"},
  {jpName:"スズラン", enName:"Lily of the valley", flowerLanguage:"「return of happiness（再び幸せが訪れる）」「sweetness（優しさ、愛らしさ）」「humility（謙遜）」「purity（純粋）」"},
  {jpName:"スターチス", enName:"Statice", flowerLanguage:"「remembrance（記憶）」「success（成功）」「sympathy（同情）」"},
  {jpName:"ストック", enName:"Stock", flowerLanguage:"「lasting beauty（永遠の美）」「bonds of affection（愛情の絆）」「contentment（満足）」「promptness（迅速さ）」"},
  {jpName:"ストレリチア", enName:"Bird of Paradise", flowerLanguage:"「magnificence（壮麗）」「faithfulness（誠実）」"},
  {jpName:"スノードロップ", enName:"Snowdrop", flowerLanguage:"「hope（希望）」「consolation（慰め）」"},
  {jpName:"スミレ", enName:"Violet", flowerLanguage:"「modesty（謙虚）」「faithfulness（誠実）」"},
  {jpName:"ゼフィランサス", enName:"Zephyr flower", flowerLanguage:"「expectation（期待）」"},
  {jpName:"ゼラニウム", enName:"Geranium", flowerLanguage:"「true friendship（真の友情）」「stupidity（愚かさ）」「gentility（育ちの良さ、上流気取り）」"},
  {jpName:"センニチコウ", enName:"Globe amaranth", flowerLanguage:"「unfading love（色あせぬ愛）」「immortality（不死、不滅）」"},
  {jpName:"タイム", enName:"Thyme", flowerLanguage:"「activity（活動、活発）」「courage（勇気）」「strength（強さ）」"},
  {jpName:"タケ", enName:"Bamboo", flowerLanguage:"「loyalty（忠誠、忠義）」「strength（強さ）」「steadfastness（不動）」"},
  {jpName:"タチアオイ", enName:"Hollyhock", flowerLanguage:"「ambition（大望、野心）」「fruitfulness（豊かな実り）」"},
  {jpName:"ダリア", enName:"Dahlia", flowerLanguage:"「dignity（威厳）」「elegance（優雅）」"},
  {jpName:"タンジー", enName:"Tansy", flowerLanguage:"「I declare war against you（あなたとの戦いを宣言する）」「resistance（抵抗）」"},
  {jpName:"タンポポ", enName:"Dandelion", flowerLanguage:"「love’s oracle（愛の神託）」「oracle（神託）」「faithfulness（誠実）」「happiness（幸福）」"},
  {jpName:"チューベローズ", enName:"Tuberose", flowerLanguage:"「dangerous pleasure（危険な快楽）」「voluptuousness（官能的）」"},
  {jpName:"チューリップ", enName:"Tulip", flowerLanguage:"「perfect lover（理想の恋人）」「fame（名声）」"},
  {jpName:"ツキミソウ / マツヨイグサ", enName:"Evening primrose", flowerLanguage:"「mute devotion（無言の愛情）」「inconstancy（移り気）」"},
  {jpName:"ツバキ", enName:"Camellia", flowerLanguage:"「admiration（敬愛、感嘆）」「perfection（完全、完璧）」"},
  {jpName:"デイジー", enName:"Daisy", flowerLanguage:"「innocence（純潔）」「beauty（美）」"},
  {jpName:"デルフィニウム", enName:"Delphinium", flowerLanguage:"「big-hearted（寛大）」「fun（楽しみ）」「ardent attachment（激しい愛着）」"},
  {jpName:"デンドロビウム", enName:"Dendrobium", flowerLanguage:"「selfish beauty（わがままな美人）」"},
  {jpName:"トケイソウ", enName:"Passion flower", flowerLanguage:"「holy love（聖なる愛）」「faith（信頼、信仰）」「religious fervour（宗教的熱情）」"},
  {jpName:"トリカブト", enName:"Monkshood", flowerLanguage:"「chivalry（騎士道）」「knight-errantry（武者修行）」"},
  {jpName:"トルコキキョウ", enName:"Lisianthus", flowerLanguage:"「appreciation（感謝）」「calming（穏やか）」"},
  {jpName:"ナシ", enName:"Pear", flowerLanguage:"「affection（愛情）」"},
  {jpName:"ナスタチウム", enName:"Nasturtium", flowerLanguage:"「patriotism（愛国心）」「victory in battle（戦いに勝つ）」"},
  {jpName:"ナズナ", enName:"Shepherd’s purse", flowerLanguage:"「I offer you my all（あなたに私のすべてを捧げます）」"},
  {jpName:"ナデシコ", enName:"Pink", flowerLanguage:"「boldness（大胆）」"},
  {jpName:"ナナカマド", enName:"Mountain Ash", flowerLanguage:"「prudence（慎重、賢明）」「I watch over you（私はあなたを見守る）」"},
  {jpName:"ニゲラ", enName:"Nigella", flowerLanguage:"「perplexity（当惑）」"},
  {jpName:"ネモフィラ", enName:"Baby blue eyes", flowerLanguage:"「success everywhere（どこでも成功）」"},
  {jpName:"ノウゼンカズラ", enName:"Trumpet vine", flowerLanguage:"「fame（名声）」"},
  {jpName:"ノコギリソウ", enName:"Yarrow", flowerLanguage:"「war（戦い）」"},
  {jpName:"パイナップル", enName:"Pineapple", flowerLanguage:"「You are perfect（あなたは完全です）」「welcome（歓迎）」"},
  {jpName:"ハイビスカス", enName:"Hibiscus", flowerLanguage:"「delicate beauty（繊細な美）」"},
  {jpName:"ハコベ", enName:"Chickweed", flowerLanguage:"「rendezvous（集合する）」"},
  {jpName:"ハス", enName:"Lotus", flowerLanguage:"「estranged love（離れゆく愛）」「eloquence（雄弁）」"},
  {jpName:"ハナズオウ", enName:"Judas tree", flowerLanguage:"「betrayal（裏切り）」「unbelief（不信仰）」"},
  {jpName:"ハナビシソウ", enName:"California poppy", flowerLanguage:"「Do not refuse me（私を拒絶しないで）」"},
  {jpName:"ハナミズキ", enName:"Dogwood", flowerLanguage:"「durability（永続性、耐久性）」「love undiminished by adversity（逆境にも耐える愛）」「Am I indifferent to you?（私があなたに関心がないとでも？）」"},
  {jpName:"バーベナ", enName:"Verbena", flowerLanguage:"「enchantment（魔力、魅力）」「sensibility（感受性）」"},
  {jpName:"バラ", enName:"Rose", flowerLanguage:"「I love you（あなたを愛してます）」「love（愛情）」「beauty（美）」「passion（情熱）」「romance（ロマンス）」"},
  {jpName:"ハルシャギク", enName:"Coreopsis", flowerLanguage:"「always cheerful（いつも陽気）」「love at first sight（一目惚れ）」"},
  {jpName:"パンジー", enName:"Pansy", flowerLanguage:"「think of me（私を思って）」「memories（思い出）」「merriment（陽気さ）」"},
  {jpName:"ヒソップ", enName:"Hyssop", flowerLanguage:"「cleanliness（清潔）」「sacrifice（犠牲）」"},
  {jpName:"ヒマワリ", enName:"Sunflower", flowerLanguage:"「adoration（愛慕、崇拝）」「false riches（偽りの富）」"},
  {jpName:"ヒヤシンス", enName:"Hyacinth", flowerLanguage:"「sports（スポーツ）」「games（ゲーム）」「rashness（無分別）」"},
  {jpName:"ヒルガオ", enName:"Bindweed", flowerLanguage:"「insinuation（ほのめかす、当てこする）」"},
  {jpName:"セイヨウヒルガオ", enName:"Convolvulus", flowerLanguage:"「bonds（絆）」"},
  {jpName:"フクシア", enName:"Fuchsia", flowerLanguage:"「humble love（つつましい愛）」「confiding love（信じる愛）」"},
  {jpName:"フクジュソウ", enName:"Amur adonis", flowerLanguage:"「sorrowful remembrance（悲しき思い出）」"},
  {jpName:"ブーゲンビリア", enName:"Bougainvillea", flowerLanguage:"「passion（情熱）」"},
  {jpName:"フジ", enName:"Wisteria", flowerLanguage:"「welcome（歓迎）」「steadfast（確固たる、しっかりした、忠実な）」"},
  {jpName:"ブドウ", enName:"Grape", flowerLanguage:"「intoxication（陶酔）」"},
  {jpName:"ブバルディア", enName:"Bouvardia", flowerLanguage:"「enthusiasm（情熱）」"},
  {jpName:"フリージア", enName:"Freesia", flowerLanguage:"「innocence（純潔）」「friendship（友情）」「trust（信頼）」"},
  {jpName:"プリムラ", enName:"Primrose", flowerLanguage:"「early youth（青春のはじめ）」「young love（青春の恋）」「I can’t live without you（あなたなしでは生きられない）」"},
  {jpName:"ブルーベル", enName:"Bluebell", flowerLanguage:"「humility（謙遜）」「constancy（不変、節操）」"},
  {jpName:"プルメリア", enName:"Plumeria", flowerLanguage:"「beauty（美）」「charm（魅力）」「grace（しとやか、上品）」"},
  {jpName:"フロックス", enName:"Phlox", flowerLanguage:"「harmony（調和）」「our souls are united（わたしたちは魂で結ばれている）」"},
  {jpName:"ベゴニア", enName:"Begonia", flowerLanguage:"「beware（注意する、用心する）」"},
  {jpName:"ペチュニア", enName:"Petunia", flowerLanguage:"「your presence soothes me（あなたと一緒なら心がやわらぐ）」"},
  {jpName:"ヘリオトロープ", enName:"Heliotrope", flowerLanguage:"「devotion（献身的な愛）」"},
  {jpName:"ベロニカ", enName:"Speedwell", flowerLanguage:"「female fidelity（女性の忠節）」"},
  {jpName:"ポインセチア", enName:"Poinsettia", flowerLanguage:"「purity（清純）」「be of good cheer（元気を出しなさい）」"},
  {jpName:"ホウセンカ", enName:"Balsam", flowerLanguage:"「impatience（短気）」「ardent love（燃えるような愛）」"},
  {jpName:"ホオズキ", enName:"Winter Cherry", flowerLanguage:"「deception（ごまかし）」"},
  {jpName:"ボダイジュ", enName:"Linden", flowerLanguage:"「conjugal love（夫婦愛）」「matrimony（結婚）」"},
  {jpName:"ボタン", enName:"Tree peony", flowerLanguage:"「bashfulness（恥じらい、はにかみ）」「compassion（思いやり）」"},
  {jpName:"ポピー", enName:"Poppy", flowerLanguage:"「oblivion（忘却）」「sleep（眠り）」「imagination（想像力）」"},
  {jpName:"マーガレット", enName:"Marguerite", flowerLanguage:"「secret love（秘密の恋）」「faith（信頼）」"},
  {jpName:"マツ", enName:"Pine", flowerLanguage:"「pity（哀れみ、同情）」「hope（希望）」"},
  {jpName:"マリーゴールド", enName:"Marigold", flowerLanguage:"「jealousy（嫉妬）」「despair（絶望）」「grief（悲嘆）」"},
  {jpName:"マンサク", enName:"Witch hazel", flowerLanguage:"「a spell（呪文、魔力）」"},
  {jpName:"ミスミソウ / ユキワリソウ", enName:"Hepatica", flowerLanguage:"「confidence（信頼、自信）」"},
  {jpName:"ミモザ", enName:"Mimosa", flowerLanguage:"「secret love（秘密の恋）」「sensitivity（感受性、思いやり）」"},
  {jpName:"ミント", enName:"Mint", flowerLanguage:"「virtue（美徳、効能）」"},
  {jpName:"ムクゲ", enName:"Rose of Sharon", flowerLanguage:"「consumed by love（恋のとりこ）」「persuasion（信念、信仰）」"},
  {jpName:"ムシトリナデシコ", enName:"Catchfly", flowerLanguage:"「snare（罠）」"},
  {jpName:"ムスカリ", enName:"Grape hyacinth", flowerLanguage:"「usefulness（有用、有益）」"},
  {jpName:"ムラサキツユクサ", enName:"Spiderwort", flowerLanguage:"「esteem not love（尊敬しているが恋愛ではない）」"},
  {jpName:"モクレン", enName:"Magnolia", flowerLanguage:"「love of nature（自然への愛）」「nobility（崇高）」「perseverance（忍耐）」「dignity（威厳）」"},
  {jpName:"モモ", enName:"Peach blossom", flowerLanguage:"「I am your captive（私はあなたのとりこ）」「unequaled qualities（比類なき素質）」"},
  {jpName:"モンステラ", enName:"Monstera", flowerLanguage:"「dedication（献身）」"},
  {jpName:"ヤグルマギク", enName:"Cornflower", flowerLanguage:"「delicacy（繊細、優美）」「refinement（上品、優雅）」"},
  {jpName:"ヤドリギ", enName:"Mistletoe", flowerLanguage:"「kiss me（私にキスして）」「I surmount difficulties（私は困難に打ち克つ）」"},
  {jpName:"ヤナギ", enName:"Willow", flowerLanguage:"「freedom（自由）」「sadness（悲哀）」"},
  {jpName:"ユリ", enName:"Lily", flowerLanguage:"「purity（純粋）」「refined beauty（洗練された美）」"},
  {jpName:"ライラック", enName:"Lilac", flowerLanguage:"「pride（誇り）」「beauty（美）」"},
  {jpName:"ラナンキュラス", enName:"Ranunculus", flowerLanguage:"「radiant charm（晴れやかな魅力）」「I am dazzled by your charms（あなたの魅力に目を奪われる）」"},
  {jpName:"ラベンダー", enName:"Lavender", flowerLanguage:"「devotion（献身的な愛）」「silence（沈黙、静寂）」「distrust（疑惑）」"},
  {jpName:"ラン", enName:"Orchid", flowerLanguage:"「love（愛情）」「beauty（美）」「refinement（上品、優雅）」「beautiful lady（美しい淑女）」"},
  {jpName:"ランタナ", enName:"Lantana", flowerLanguage:"「rigor（厳格）」"},
  {jpName:"リンゴ", enName:"Apple blossom", flowerLanguage:"「preference（優先、好み）」"},
  {jpName:"リンドウ", enName:"Gentian", flowerLanguage:"「I love you best when you are sad（悲しんでいるあなたを愛する）」「loveliness（愛らしい）」「intrinsic worth（固有の価値）」"},
  {jpName:"ルドベキア", enName:"Rudbeckia", flowerLanguage:"「justice（正義、公正）」"},
  {jpName:"ルピナス", enName:"Lupine", flowerLanguage:"「imagination（想像力）」「always happy（いつも幸せ）」「voraciousness（貪欲）」"},
  {jpName:"レモン", enName:"Lemon", flowerLanguage:"「fidelity in love（誠実な愛）」「discretion（思慮分別、自由裁量）」"},
  {jpName:"レンギョウ", enName:"Forsythia", flowerLanguage:"「anticipation（期待）」"},
  {jpName:"レンゲソウ", enName:"Chinese milk vetch", flowerLanguage:"「your presence softens my pains（あなたと一緒なら苦痛がやわらぐ）」"},
  {jpName:"ロベリア", enName:"Lobelia", flowerLanguage:"「malevolence（悪意）」"},
  {jpName:"ワスレナグサ", enName:"Forget-me-not", flowerLanguage:"「true love（真実の愛）」「memories（思い出）」"},
];
