const FLOWER_LIST = [
  {jpName:"アイビー / アヤメ", enName:"Ivy", description:"「friendship（友情）」「fidelity（忠実、貞節）」「marriage（結婚）」「wedded love（夫婦愛）」"},
  {jpName:"アイリス", enName:"Iris", description:"「message（伝言、メッセージ）」「hope（希望）」「faith（信頼）」「friendship（友情）」「wisdom（知恵、賢さ）」"},
  {jpName:"アガパンサス", enName:"Agapanthus", description:"「love letter（ラブレター）」"},
  {jpName:"アカンサス", enName:"Acanthus", description:"「art（芸術）」「artifice（技巧）」"},
  {jpName:"アキノキリンソウ", enName:"Goldenrod", description:"「precaution（予防、用心、警戒）」「encouragement（励まし）」"},
  {jpName:"アサガオ", enName:"Morning glory", description:"「love in vain（はかない恋）」「affection（愛情）」"},
  {jpName:"アザミ", enName:"Thistle", description:"「independence（独立）」「nobility of character（人格の高潔さ）」「austerity（厳格）」「misanthropy（人間嫌い）」"},
  {jpName:"アザレア/ツツジ", enName:"Azalea", description:"「temperance（節制、禁酒）」「take care of yourself for me（私のためにお体を大切に）」「fragility（もろさ、はかなさ）」"},
  {jpName:"アジサイ", enName:"Hydrangea", description:"「heartlessness（冷酷）」「boastfulness（高慢）」「You are cold（あなたは冷たい人）」"},
  {jpName:"アスター / エゾギク", enName:"China aster", description:"「variety（多様性、変化）」「fidelity（忠実、貞節）」「I will think of you（私はあなたを想うでしょう）」"},
  {jpName:"アネモネ", enName:"Anemone", description:"「anticipation（期待）」「forsaken（見捨てられる、見放される）」"},
  {jpName:"アマリリス", enName:"Amaryllis", description:"「pride（誇り）」「splendid beauty（輝くばかりの美しさ）」"},
  {jpName:"アリウム", enName:"Allium", description:"「prosperity（繁栄）」「good fortune（幸運）」「humility（謙遜）」"},
  {jpName:"アルストロメリア", enName:"Alstroemeria", description:"「friendship（友情）」「devotion（献身的な愛）」"},
  {jpName:"アルメリア", enName:"Thrift", description:"「sympathy（同情、思いやり、共感）」"},
  {jpName:"アロエ", enName:"Aloe", description:"「bitterness（苦痛）」「grief（悲嘆）」"},
  {jpName:"アンスリウム", enName:"Anthurium", description:"「hospitality（温かいもてなし）」"},
  {jpName:"アンズ", enName:"Apricot blossom", description:"「timid love（臆病な愛）」「doubt（疑い）」「distrust（疑惑）」"},
  {jpName:"イチゴ", enName:"Strawberry", description:"「esteem and love（尊重と愛情）」「perfect goodness（完全なる善）」"},
  {jpName:"イヌサフラン / コルチカム", enName:"Meadow saffron", description:"「My best days are past（私の最良の日々は過ぎ去った）」"},
  {jpName:"イベリス", enName:"Candytuft", description:"「indifference（無関心）」"},
  {jpName:"ウメ", enName:"Plum blossom", description:"「Keep your promise（約束を守る）」「fidelity（忠実）」「beauty and longevity（美と長寿）」"},
  {jpName:"エーデルワイス", enName:"Edelweiss", description:"「noble courage（高潔な勇気）」「daring（大胆不敵）」"},
  {jpName:"エニシダ", enName:"Broom", description:"「humility（謙遜、卑下）」「neatness（清潔）」"},
  {jpName:"エリカ", enName:"Heath", description:"「solitude（孤独）」"},
  {jpName:"オジギソウ", enName:"Sensitive plant", description:"「delicate feelings（繊細な感情）」「sensitiveness（感受性、鋭敏）」"},
  {jpName:"オシロイバナ", enName:"Marvel of Peru", description:"「timidity（臆病）」"},
  {jpName:"オダマキ", enName:"Columbine", description:"「folly（愚か）」"},
  {jpName:"オトギリソウ", enName:"St. John’s wort", description:"「superstition（迷信）」「animosity（敵意）」"},
  {jpName:"オーニソガラム", enName:"Star of Bethlehem", description:"「purity（純粋）」「reconciliation（和解）」「hope（希望）」"},
  {jpName:"オリーブ", enName:"Olive", description:"「peace（平和）」「wisdom（知恵、賢さ）」"},
  {jpName:"オレンジ", enName:"Orange", description:"「purity（純粋）」「Your purity equals your loveliness（あなたの純粋さはあなたの愛らしさと釣り合っている）」"},
  {jpName:"カエデ / モミジ", enName:"Maple", description:"「reserve（蓄え、遠慮）」"},
  {jpName:"カスミソウ", enName:"Baby’s breath", description:"「everlasting love（永遠の愛）」「purity of heart（清らかな心）」「innocence（純潔）」"},
  {jpName:"カタバミ", enName:"Wood sorrel", description:"「joy（喜び）」「maternal tenderness（母のやさしさ）」"},
  {jpName:"カトレア", enName:"Cattleya", description:"「mature charm（成熟した大人の魅力）」"},
  {jpName:"カーネーション", enName:"Carnation", description:"「fascination（魅惑、魅力）」「love（愛情）」「distinction（卓越、名声）」"},
  {jpName:"ガーベラ", enName:"Gerbera", description:"「cheerfulness（上機嫌、元気）」「beauty（美）」"},
  {jpName:"カモミール", enName:"Chamomile", description:"「patience in adversity（逆境に耐える）」「energy in adversity（逆境で生まれる力）」"},
  {jpName:"カラー", enName:"Calla lily", description:"「magnificent beauty（華麗なる美）」「feminine modesty（女性のしとやかさ）」"},
  {jpName:"カランコエ", enName:"Kalanchoe", description:"「popularity（人気、人望）」"},
  {jpName:"カルミア", enName:"Mountain laurel", description:"「ambition（大望、野心）」「treachery（裏切り）」"},
  {jpName:"カンナ", enName:"Canna", description:"「paranoia（妄想）」「suspicion（疑い）」"},
  {jpName:"カンパニュラ", enName:"Canterbury bells", description:"「gratitude（感謝）」「constancy（不変、節操）」"},
  {jpName:"キキョウ", enName:"Balloon flower", description:"「endless love（永遠の愛）」「honesty（正直、誠実）」「the return of a friend is desired（友の帰りを願う）」「obedience（従順）」"},
  {jpName:"キク", enName:"Chrysanthemum", description:"「cheerfulness（上機嫌、元気）」「You’re a wonderful friend（あなたはとても素晴らしい友達）」"},
  {jpName:"キョウチクトウ", enName:"Oleander", description:"「caution（用心）」「beware（注意する、用心する）」"},
  {jpName:"キンギョソウ", enName:"Snapdragon", description:"「graciousness（上品さ、優雅さ）」「deception（ごまかし）」"},
  {jpName:"キンセンカ", enName:"Calendula", description:"「grief（悲嘆）」「despair（絶望）」「sorrow（悲しみ、悲哀）」"},
  {jpName:"クチナシ", enName:"Cape jasmine", description:"「I’m too happy（私はとても幸せです）」「transport of joy（喜びを運ぶ）」"},
  {jpName:"グラジオラス", enName:"Gladiolus", description:"「strength of character（人格的強さ）」「sincerity（誠実）」「preparedness（準備）」「remembrance（記憶）」"},
  {jpName:"クリスマスローズ", enName:"Christmas rose", description:"「relieve my anxiety（私の不安をやわらげて）」"},
  {jpName:"クレマチス", enName:"Clematis", description:"「mental beauty（精神の美）」「ingenuity（創意工夫）」「artifice（策略）」"},
  {jpName:"クロッカス", enName:"Crocus", description:"「youthful gladness（青春の喜び）」「cheerfulness（上機嫌、元気）」"},
  {jpName:"クローバー", enName:"Clover", description:"「think of me（私を思って）」"},
  {jpName:"ケイトウ", enName:"Cockscomb", description:"「foppery（〔男の〕おしゃれ）」「affectation（気取り）」「singularity（風変わり）」"},
  {jpName:"ゲッケイジュ", enName:"Laurel", description:"「glory（栄光）」「victory（勝利）」"},
  {jpName:"コスモス", enName:"Cosmos", description:"「harmony（調和）」「peace（平和）」「modesty（謙虚）」「the joys that love and life can bring（愛や人生がもたらす喜び）」「beautiful（美しい）」"},
  {jpName:"コチョウラン", enName:"Phalaenopsis", description:"「love（愛情）」「beauty（美）」「luxury（高級、豪華さ）」「refinement（上品、優雅）」"},
  {jpName:"ゴボウ", enName:"Burdock", description:"「touch me not（私にさわらないで）」「importunity（しつこくせがむ）」"},
  {jpName:"サイネリア / シネラリア", enName:"Cineraria", description:"「always delightful（いつも愉快）」"},
  {jpName:"サクラ", enName:"Cherry blossom", description:"「spiritual beauty（精神の美）」「a good education（優れた教育）」"},
  {jpName:"ザクロ", enName:"Pomegranate", description:"「mature elegance（円熟した優雅さ）」"},
  {jpName:"サフラン", enName:"Saffron crocus", description:"「mirth（歓喜）」「beware of excess（過度をつつしめ）」「Do not abuse（濫用するな）」"},
  {jpName:"サボテン", enName:"Cactus", description:"「endurance（忍耐）」「ardent love（燃えるような愛）」「grandeur（雄大、偉大）」「warmth（優しさ、暖かさ）」"},
  {jpName:"サルビア", enName:"Sage", description:"「esteem（尊敬、尊重）」「wisdom（知恵、賢さ）」「domestic virtue（家庭の徳）」"},
  {jpName:"サンザシ", enName:"Hawthorn", description:"「hope（希望）」"},
  {jpName:"シオン", enName:"Aster", description:"「patience（忍耐）」「daintiness（優美、繊細）」「symbol of love（愛の象徴）」"},
  {jpName:"ジギタリス", enName:"Foxglove", description:"「insincerity（不誠実）」"},
  {jpName:"シクラメン", enName:"Cyclamen", description:"「timid hope（遠慮がちな期待）」「shyness（内気、はにかみ）」「resignation and good-bye（退職と別れの言葉）」"},
  {jpName:"ジニア", enName:"Zinnia", description:"「thoughts of absent friends（不在の友を思う）」「I mourn your absence（あなたの不在を悲しむ）」"},
  {jpName:"シャクナゲ", enName:"Rhododendron", description:"「danger（危険）」「caution（用心）」「beware（注意する、用心する）」"},
  {jpName:"シャクヤク", enName:"Chinese peony", description:"「bashfulness（恥じらい、はにかみ）」「compassion（思いやり）」"},
  {jpName:"ジャスミン", enName:"Jasmine", description:"「amiability（愛想のよさ）」「You are cheerful and graceful（あなたは朗らかで気品がある）」"},
  {jpName:"ジンチョウゲ", enName:"Daphne odora", description:"「glory（栄光）」「immortality（不死、不滅）」"},
  {jpName:"シンビジウム", enName:"Cymbidium", description:"「magnificence（壮麗）」「gorgeous love（華やかな恋）」"},
  {jpName:"スイカズラ", enName:"Honeysuckle", description:"「bonds of love（愛の絆）」「devotion（献身的な愛）」"},
  {jpName:"スイセン", enName:"Narcissus", description:"「self-love（自己愛）」「egotism（自己中心、うぬぼれ）」「unrequited love（報われぬ恋）」"},
  {jpName:"スイートピー", enName:"Sweet pea", description:"「departure（門出）」「good-bye（別れの言葉）」「delicate pleasure（ほのかな喜び）」「tender memory（優しい思い出）」「blissful pleasure（至福の喜び）」"},
  {jpName:"スイレン", enName:"Water lily", description:"「purity of heart（清らかな心）」"},
  {jpName:"スカビオサ", enName:"Scabiosa", description:"「unfortunate love（不幸な愛）」「I have lost all（私はすべてを失った）」"},
  {jpName:"プラタナス", enName:"Sycamore", description:"「genius（天才）」「curiosity（好奇心）」"},
  {jpName:"スズラン", enName:"Lily of the valley", description:"「return of happiness（再び幸せが訪れる）」「sweetness（優しさ、愛らしさ）」「humility（謙遜）」「purity（純粋）」"},
  {jpName:"スターチス", enName:"Statice", description:"「remembrance（記憶）」「success（成功）」「sympathy（同情）」"},
  {jpName:"ストック", enName:"Stock", description:"「lasting beauty（永遠の美）」「bonds of affection（愛情の絆）」「contentment（満足）」「promptness（迅速さ）」"},
  {jpName:"ストレリチア", enName:"Bird of Paradise", description:"「magnificence（壮麗）」「faithfulness（誠実）」"},
  {jpName:"スノードロップ", enName:"Snowdrop", description:"「hope（希望）」「consolation（慰め）」"},
  {jpName:"スミレ", enName:"Violet", description:"「modesty（謙虚）」「faithfulness（誠実）」"},
  {jpName:"ゼフィランサス", enName:"Zephyr flower", description:"「expectation（期待）」"},
  {jpName:"ゼラニウム", enName:"Geranium", description:"「true friendship（真の友情）」「stupidity（愚かさ）」「gentility（育ちの良さ、上流気取り）」"},
  {jpName:"センニチコウ", enName:"Globe amaranth", description:"「unfading love（色あせぬ愛）」「immortality（不死、不滅）」"},
  {jpName:"タイム", enName:"Thyme", description:"「activity（活動、活発）」「courage（勇気）」「strength（強さ）」"},
  {jpName:"タケ", enName:"Bamboo", description:"「loyalty（忠誠、忠義）」「strength（強さ）」「steadfastness（不動）」"},
  {jpName:"タチアオイ", enName:"Hollyhock", description:"「ambition（大望、野心）」「fruitfulness（豊かな実り）」"},
  {jpName:"ダリア", enName:"Dahlia", description:"「dignity（威厳）」「elegance（優雅）」"},
  {jpName:"タンジー", enName:"Tansy", description:"「I declare war against you（あなたとの戦いを宣言する）」「resistance（抵抗）」"},
  {jpName:"タンポポ", enName:"Dandelion", description:"「love’s oracle（愛の神託）」「oracle（神託）」「faithfulness（誠実）」「happiness（幸福）」"},
  {jpName:"チューベローズ", enName:"Tuberose", description:"「dangerous pleasure（危険な快楽）」「voluptuousness（官能的）」"},
  {jpName:"チューリップ", enName:"Tulip", description:"「perfect lover（理想の恋人）」「fame（名声）」"},
  {jpName:"ツキミソウ / マツヨイグサ", enName:"Evening primrose", description:"「mute devotion（無言の愛情）」「inconstancy（移り気）」"},
  {jpName:"ツバキ", enName:"Camellia", description:"「admiration（敬愛、感嘆）」「perfection（完全、完璧）」"},
  {jpName:"デイジー", enName:"Daisy", description:"「innocence（純潔）」「beauty（美）」"},
  {jpName:"デルフィニウム", enName:"Delphinium", description:"「big-hearted（寛大）」「fun（楽しみ）」「ardent attachment（激しい愛着）」"},
  {jpName:"デンドロビウム", enName:"Dendrobium", description:"「selfish beauty（わがままな美人）」"},
  {jpName:"トケイソウ", enName:"Passion flower", description:"「holy love（聖なる愛）」「faith（信頼、信仰）」「religious fervour（宗教的熱情）」"},
  {jpName:"トリカブト", enName:"Monkshood", description:"「chivalry（騎士道）」「knight-errantry（武者修行）」"},
  {jpName:"トルコキキョウ", enName:"Lisianthus", description:"「appreciation（感謝）」「calming（穏やか）」"},
  {jpName:"ナシ", enName:"Pear", description:"「affection（愛情）」"},
  {jpName:"ナスタチウム", enName:"Nasturtium", description:"「patriotism（愛国心）」「victory in battle（戦いに勝つ）」"},
  {jpName:"ナズナ", enName:"Shepherd’s purse", description:"「I offer you my all（あなたに私のすべてを捧げます）」"},
  {jpName:"ナデシコ", enName:"Pink", description:"「boldness（大胆）」"},
  {jpName:"ナナカマド", enName:"Mountain Ash", description:"「prudence（慎重、賢明）」「I watch over you（私はあなたを見守る）」"},
  {jpName:"ニゲラ", enName:"Nigella", description:"「perplexity（当惑）」"},
  {jpName:"ネモフィラ", enName:"Baby blue eyes", description:"「success everywhere（どこでも成功）」"},
  {jpName:"ノウゼンカズラ", enName:"Trumpet vine", description:"「fame（名声）」"},
  {jpName:"ノコギリソウ", enName:"Yarrow", description:"「war（戦い）」"},
  {jpName:"パイナップル", enName:"Pineapple", description:"「You are perfect（あなたは完全です）」「welcome（歓迎）」"},
  {jpName:"ハイビスカス", enName:"Hibiscus", description:"「delicate beauty（繊細な美）」"},
  {jpName:"ハコベ", enName:"Chickweed", description:"「rendezvous（集合する）」"},
  {jpName:"ハス", enName:"Lotus", description:"「estranged love（離れゆく愛）」「eloquence（雄弁）」"},
  {jpName:"ハナズオウ", enName:"Judas tree", description:"「betrayal（裏切り）」「unbelief（不信仰）」"},
  {jpName:"ハナビシソウ", enName:"California poppy", description:"「Do not refuse me（私を拒絶しないで）」"},
  {jpName:"ハナミズキ", enName:"Dogwood", description:"「durability（永続性、耐久性）」「love undiminished by adversity（逆境にも耐える愛）」「Am I indifferent to you?（私があなたに関心がないとでも？）」"},
  {jpName:"バーベナ", enName:"Verbena", description:"「enchantment（魔力、魅力）」「sensibility（感受性）」"},
  {jpName:"バラ", enName:"Rose", description:"「I love you（あなたを愛してます）」「love（愛情）」「beauty（美）」「passion（情熱）」「romance（ロマンス）」"},
  {jpName:"ハルシャギク", enName:"Coreopsis", description:"「always cheerful（いつも陽気）」「love at first sight（一目惚れ）」"},
  {jpName:"パンジー", enName:"Pansy", description:"「think of me（私を思って）」「memories（思い出）」「merriment（陽気さ）」"},
  {jpName:"ヒソップ", enName:"Hyssop", description:"「cleanliness（清潔）」「sacrifice（犠牲）」"},
  {jpName:"ヒマワリ", enName:"Sunflower", description:"「adoration（愛慕、崇拝）」「false riches（偽りの富）」"},
  {jpName:"ヒヤシンス", enName:"Hyacinth", description:"「sports（スポーツ）」「games（ゲーム）」「rashness（無分別）」"},
  {jpName:"ヒルガオ", enName:"Bindweed", description:"「insinuation（ほのめかす、当てこする）」"},
  {jpName:"セイヨウヒルガオ", enName:"Convolvulus", description:"「bonds（絆）」"},
  {jpName:"フクシア", enName:"Fuchsia", description:"「humble love（つつましい愛）」「confiding love（信じる愛）」"},
  {jpName:"フクジュソウ", enName:"Amur adonis", description:"「sorrowful remembrance（悲しき思い出）」"},
  {jpName:"ブーゲンビリア", enName:"Bougainvillea", description:"「passion（情熱）」"},
  {jpName:"フジ", enName:"Wisteria", description:"「welcome（歓迎）」「steadfast（確固たる、しっかりした、忠実な）」"},
  {jpName:"ブドウ", enName:"Grape", description:"「intoxication（陶酔）」"},
  {jpName:"ブバルディア", enName:"Bouvardia", description:"「enthusiasm（情熱）」"},
  {jpName:"フリージア", enName:"Freesia", description:"「innocence（純潔）」「friendship（友情）」「trust（信頼）」"},
  {jpName:"プリムラ", enName:"Primrose", description:"「early youth（青春のはじめ）」「young love（青春の恋）」「I can’t live without you（あなたなしでは生きられない）」"},
  {jpName:"ブルーベル", enName:"Bluebell", description:"「humility（謙遜）」「constancy（不変、節操）」"},
  {jpName:"プルメリア", enName:"Plumeria", description:"「beauty（美）」「charm（魅力）」「grace（しとやか、上品）」"},
  {jpName:"フロックス", enName:"Phlox", description:"「harmony（調和）」「our souls are united（わたしたちは魂で結ばれている）」"},
  {jpName:"ベゴニア", enName:"Begonia", description:"「beware（注意する、用心する）」"},
  {jpName:"ペチュニア", enName:"Petunia", description:"「your presence soothes me（あなたと一緒なら心がやわらぐ）」"},
  {jpName:"ヘリオトロープ", enName:"Heliotrope", description:"「devotion（献身的な愛）」"},
  {jpName:"ベロニカ", enName:"Speedwell", description:"「female fidelity（女性の忠節）」"},
  {jpName:"ポインセチア", enName:"Poinsettia", description:"「purity（清純）」「be of good cheer（元気を出しなさい）」"},
  {jpName:"ホウセンカ", enName:"Balsam", description:"「impatience（短気）」「ardent love（燃えるような愛）」"},
  {jpName:"ホオズキ", enName:"Winter Cherry", description:"「deception（ごまかし）」"},
  {jpName:"ボダイジュ", enName:"Linden", description:"「conjugal love（夫婦愛）」「matrimony（結婚）」"},
  {jpName:"ボタン", enName:"Tree peony", description:"「bashfulness（恥じらい、はにかみ）」「compassion（思いやり）」"},
  {jpName:"ポピー", enName:"Poppy", description:"「oblivion（忘却）」「sleep（眠り）」「imagination（想像力）」"},
  {jpName:"マーガレット", enName:"Marguerite", description:"「secret love（秘密の恋）」「faith（信頼）」"},
  {jpName:"マツ", enName:"Pine", description:"「pity（哀れみ、同情）」「hope（希望）」"},
  {jpName:"マリーゴールド", enName:"Marigold", description:"「jealousy（嫉妬）」「despair（絶望）」「grief（悲嘆）」"},
  {jpName:"マンサク", enName:"Witch hazel", description:"「a spell（呪文、魔力）」"},
  {jpName:"ミスミソウ / ユキワリソウ", enName:"Hepatica", description:"「confidence（信頼、自信）」"},
  {jpName:"ミモザ", enName:"Mimosa", description:"「secret love（秘密の恋）」「sensitivity（感受性、思いやり）」"},
  {jpName:"ミント", enName:"Mint", description:"「virtue（美徳、効能）」"},
  {jpName:"ムクゲ", enName:"Rose of Sharon", description:"「consumed by love（恋のとりこ）」「persuasion（信念、信仰）」"},
  {jpName:"ムシトリナデシコ", enName:"Catchfly", description:"「snare（罠）」"},
  {jpName:"ムスカリ", enName:"Grape hyacinth", description:"「usefulness（有用、有益）」"},
  {jpName:"ムラサキツユクサ", enName:"Spiderwort", description:"「esteem not love（尊敬しているが恋愛ではない）」"},
  {jpName:"モクレン", enName:"Magnolia", description:"「love of nature（自然への愛）」「nobility（崇高）」「perseverance（忍耐）」「dignity（威厳）」"},
  {jpName:"モモ", enName:"Peach blossom", description:"「I am your captive（私はあなたのとりこ）」「unequaled qualities（比類なき素質）」"},
  {jpName:"モンステラ", enName:"Monstera", description:"「dedication（献身）」"},
  {jpName:"ヤグルマギク", enName:"Cornflower", description:"「delicacy（繊細、優美）」「refinement（上品、優雅）」"},
  {jpName:"ヤドリギ", enName:"Mistletoe", description:"「kiss me（私にキスして）」「I surmount difficulties（私は困難に打ち克つ）」"},
  {jpName:"ヤナギ", enName:"Willow", description:"「freedom（自由）」「sadness（悲哀）」"},
  {jpName:"ユリ", enName:"Lily", description:"「purity（純粋）」「refined beauty（洗練された美）」"},
  {jpName:"ライラック", enName:"Lilac", description:"「pride（誇り）」「beauty（美）」"},
  {jpName:"ラナンキュラス", enName:"Ranunculus", description:"「radiant charm（晴れやかな魅力）」「I am dazzled by your charms（あなたの魅力に目を奪われる）」"},
  {jpName:"ラベンダー", enName:"Lavender", description:"「devotion（献身的な愛）」「silence（沈黙、静寂）」「distrust（疑惑）」"},
  {jpName:"ラン", enName:"Orchid", description:"「love（愛情）」「beauty（美）」「refinement（上品、優雅）」「beautiful lady（美しい淑女）」"},
  {jpName:"ランタナ", enName:"Lantana", description:"「rigor（厳格）」"},
  {jpName:"リンゴ", enName:"Apple blossom", description:"「preference（優先、好み）」"},
  {jpName:"リンドウ", enName:"Gentian", description:"「I love you best when you are sad（悲しんでいるあなたを愛する）」「loveliness（愛らしい）」「intrinsic worth（固有の価値）」"},
  {jpName:"ルドベキア", enName:"Rudbeckia", description:"「justice（正義、公正）」"},
  {jpName:"ルピナス", enName:"Lupine", description:"「imagination（想像力）」「always happy（いつも幸せ）」「voraciousness（貪欲）」"},
  {jpName:"レモン", enName:"Lemon", description:"「fidelity in love（誠実な愛）」「discretion（思慮分別、自由裁量）」"},
  {jpName:"レンギョウ", enName:"Forsythia", description:"「anticipation（期待）」"},
  {jpName:"レンゲソウ", enName:"Chinese milk vetch", description:"「your presence softens my pains（あなたと一緒なら苦痛がやわらぐ）」"},
  {jpName:"ロベリア", enName:"Lobelia", description:"「malevolence（悪意）」"},
  {jpName:"ワスレナグサ", enName:"Forget-me-not", description:"「true love（真実の愛）」「memories（思い出）」"},
];


const CONSTELLATION_LIST = [
  {jpName:"アンドロメダ座", enName:"Andromeda", description:"アンドロメダー（神話の人物） ― アンドロメダ座β星", threeCodeName:"And", fourCodeName:"Andr"},
  {jpName:"ポンプ座", enName:"Antlia", description:"真空ポンプ ― ポンプ座α星", threeCodeName:"Ant", fourCodeName:"Antl"},
  {jpName:"ふうちょう座", enName:"Apus", description:"極楽鳥 ― ふうちょう座α星", threeCodeName:"Aps", fourCodeName:"Apus"},
  {jpName:"みずがめ座", enName:"Aquarius", description:"水瓶 ― みずがめ座β星", threeCodeName:"Aqr", fourCodeName:"Aqar"},
  {jpName:"わし座", enName:"Aquila", description:"ワシ ― アルタイル", threeCodeName:"Aql", fourCodeName:"Aqil"},
  {jpName:"さいだん座", enName:"Ara", description:"祭壇 ― さいだん座β星", threeCodeName:"Ara", fourCodeName:"Arae"},
  {jpName:"おひつじ座", enName:"Aries", description:"ヒツジ ― おひつじ座α星", threeCodeName:"Ari", fourCodeName:"Arie"},
  {jpName:"ぎょしゃ座", enName:"Auriga", description:"御者 ― カペラ", threeCodeName:"Aur", fourCodeName:"Auri"},
  {jpName:"うしかい座", enName:"Bootes", description:"牛飼い ― アークトゥルス", threeCodeName:"Boo", fourCodeName:"Boot"},
  {jpName:"ちょうこくぐ座", enName:"Caelum", description:"彫刻刀 ― ちょうこくぐ座α星", threeCodeName:"Cae", fourCodeName:"Cael"},
  {jpName:"きりん座", enName:"Camelopardalis", description:"キリン ― きりん座β星", threeCodeName:"Cam", fourCodeName:"Caml"},
  {jpName:"かに座", enName:"Cancer", description:"カニ ― かに座β星", threeCodeName:"Cnc", fourCodeName:"Canc"},
  {jpName:"りょうけん座", enName:"Canes Venatici", description:"猟犬 ― りょうけん座α星", threeCodeName:"CVn", fourCodeName:"CVen"},
  {jpName:"おおいぬ座", enName:"Canis Major", description:"大きいイヌ ― シリウス", threeCodeName:"CMa", fourCodeName:"CMaj"},
  {jpName:"こいぬ座", enName:"Canis Minor", description:"小さいイヌ ― プロキオン", threeCodeName:"CMi", fourCodeName:"CMin"},
  {jpName:"やぎ座", enName:"Capricornus", description:"ヤギ ― やぎ座δ星", threeCodeName:"Cap", fourCodeName:"Capr"},
  {jpName:"りゅうこつ座", enName:"Carina", description:"船の竜骨 ― カノープス", threeCodeName:"Car", fourCodeName:"Cari"},
  {jpName:"カシオペヤ座", enName:"Cassiopeia", description:"カッシオペイア（神話の人物） ― カシオペヤ座α星", threeCodeName:"Cas", fourCodeName:"Cass"},
  {jpName:"ケンタウルス座", enName:"Centaurus", description:"ケンタウロス ― ケンタウルス座α星", threeCodeName:"Cen", fourCodeName:"Cent"},
  {jpName:"ケフェウス座", enName:"Cepheus", description:"ケーペウス（神話の人物） ― ケフェウス座α星", threeCodeName:"Cep", fourCodeName:"Ceph"},
  {jpName:"くじら座", enName:"Cetus", description:"海の怪物（後にクジラ） ― くじら座β星", threeCodeName:"Cet", fourCodeName:"Ceti"},
  {jpName:"カメレオン座", enName:"Chamaeleon", description:"カメレオン ― カメレオン座α星", threeCodeName:"Cha", fourCodeName:"Cham"},
  {jpName:"コンパス座", enName:"Circinus", description:"製図用のディバイダ ― コンパス座α星", threeCodeName:"Cir", fourCodeName:"Circ"},
  {jpName:"はと座", enName:"Columba", description:"ノアのハト ― はと座α星", threeCodeName:"Col", fourCodeName:"Colm"},
  {jpName:"かみのけ座", enName:"Coma Berenices", description:"ベレニケ2世の髪の毛 ― かみのけ座β星", threeCodeName:"Com", fourCodeName:"Coma"},
  {jpName:"みなみのかんむり座", enName:"Corona Australis", description:"南の冠 ― みなみのかんむり座α星", threeCodeName:"CrA", fourCodeName:"CorA"},
  {jpName:"かんむり座", enName:"Corona Borealis", description:"北の冠 ― かんむり座α星", threeCodeName:"CrB", fourCodeName:"CorB"},
  {jpName:"からす座", enName:"Corvus", description:"カラス ― からす座γ星", threeCodeName:"Crv", fourCodeName:"Corv"},
  {jpName:"コップ座", enName:"Crater", description:"杯 ― コップ座δ星", threeCodeName:"Crt", fourCodeName:"Crat"},
  {jpName:"みなみじゅうじ座", enName:"Crux", description:"十字 ― みなみじゅうじ座α星", threeCodeName:"Cru", fourCodeName:"Cruc"},
  {jpName:"はくちょう座", enName:"Cygnus", description:"ハクチョウ ― デネブ", threeCodeName:"Cyg", fourCodeName:"Cygn"},
  {jpName:"いるか座", enName:"Delphinus", description:"イルカ ― いるか座β星", threeCodeName:"Del", fourCodeName:"Dlph"},
  {jpName:"かじき座", enName:"Dorado", description:"シイラ ― かじき座α星", threeCodeName:"Dor", fourCodeName:"Dora"},
  {jpName:"りゅう座", enName:"Draco", description:"竜 ― りゅう座γ星", threeCodeName:"Dra", fourCodeName:"Drac"},
  {jpName:"こうま座", enName:"Equuleus", description:"仔ウマ ― こうま座α星", threeCodeName:"Equ", fourCodeName:"Equl"},
  {jpName:"エリダヌス座", enName:"Eridanus", description:"エーリダノス川 ― アケルナル", threeCodeName:"Eri", fourCodeName:"Erid"},
  {jpName:"ろ座", enName:"Fornax", description:"炉 ― ろ座α星", threeCodeName:"For", fourCodeName:"Forn"},
  {jpName:"ふたご座", enName:"Gemini", description:"双子（神話の人物） ― ポルックス", threeCodeName:"Gem", fourCodeName:"Gemi"},
  {jpName:"つる座", enName:"Grus", description:"ツル ― つる座α星", threeCodeName:"Gru", fourCodeName:"Grus"},
  {jpName:"ヘルクレス座", enName:"Hercules", description:"ヘーラクレース（神話の人物） ― ヘルクレス座β星", threeCodeName:"Her", fourCodeName:"Herc"},
  {jpName:"とけい座", enName:"Horologium", description:"振り子時計 ― とけい座α星", threeCodeName:"Hor", fourCodeName:"Horo"},
  {jpName:"うみへび座", enName:"Hydra", description:"ヒュドラー（神話の生物） ― アルファルド", threeCodeName:"Hya", fourCodeName:"Hyda"},
  {jpName:"みずへび座", enName:"Hydrus", description:"雄のウミヘビ ― みずへび座β星", threeCodeName:"Hyi", fourCodeName:"Hydi"},
  {jpName:"インディアン座", enName:"Indus", description:"インディアン ― インディアン座α星", threeCodeName:"Ind", fourCodeName:"Indi"},
  {jpName:"とかげ座", enName:"Lacerta", description:"トカゲ ― とかげ座α星", threeCodeName:"Lac", fourCodeName:"Lacr"},
  {jpName:"しし座", enName:"Leo", description:"ライオン ― レグルス", threeCodeName:"Leo", fourCodeName:"Leon"},
  {jpName:"こじし座", enName:"Leo Minor", description:"小さいライオン ― こじし座46番星", threeCodeName:"LMi", fourCodeName:"LMin"},
  {jpName:"うさぎ座", enName:"Lepus", description:"ウサギ ― うさぎ座α星", threeCodeName:"Lep", fourCodeName:"Leps"},
  {jpName:"てんびん座", enName:"Libra", description:"天秤 ― てんびん座β星", threeCodeName:"Lib", fourCodeName:"Libr"},
  {jpName:"おおかみ座", enName:"Lupus", description:"オオカミ ― おおかみ座α星", threeCodeName:"Lup", fourCodeName:"Lupi"},
  {jpName:"やまねこ座", enName:"Lynx", description:"ヤマネコ ― やまねこ座α星", threeCodeName:"Lyn", fourCodeName:"Lync"},
  {jpName:"こと座", enName:"Lyra", description:"竪琴 ― ベガ", threeCodeName:"Lyr", fourCodeName:"Lyra"},
  {jpName:"テーブルさん座", enName:"Mensa", description:"テーブルマウンテン ― テーブルさん座α星", threeCodeName:"Men", fourCodeName:"Mens"},
  {jpName:"けんびきょう座", enName:"Microscopium", description:"顕微鏡 ― けんびきょう座γ星", threeCodeName:"Mic", fourCodeName:"Micr"},
  {jpName:"いっかくじゅう座", enName:"Monoceros", description:"ユニコーン ― いっかくじゅう座β星", threeCodeName:"Mon", fourCodeName:"Mono"},
  {jpName:"はえ座", enName:"Musca", description:"ハエ ― はえ座α星", threeCodeName:"Mus", fourCodeName:"Musc"},
  {jpName:"じょうぎ座", enName:"Norma", description:"定規 ― じょうぎ座γ2星", threeCodeName:"Nor", fourCodeName:"Norm"},
  {jpName:"はちぶんぎ座", enName:"Octans", description:"八分儀 ― はちぶんぎ座ν星", threeCodeName:"Oct", fourCodeName:"Octn"},
  {jpName:"へびつかい座", enName:"Ophiuchus", description:"蛇使い ― へびつかい座α星", threeCodeName:"Oph", fourCodeName:"Ophi"},
  {jpName:"オリオン座", enName:"Orion", description:"オーリーオーン（神話の人物） ― リゲル", threeCodeName:"Ori", fourCodeName:"Orio"},
  {jpName:"くじゃく座", enName:"Pavo", description:"クジャク ― くじゃく座α星", threeCodeName:"Pav", fourCodeName:"Pavo"},
  {jpName:"ペガスス座", enName:"Pegasus", description:"ペーガソス（神話の生物） ― ペガスス座ε星", threeCodeName:"Peg", fourCodeName:"Pegs"},
  {jpName:"ペルセウス座", enName:"Perseus", description:"ペルセウス（神話の人物） ― ペルセウス座α星", threeCodeName:"Per", fourCodeName:"Pers"},
  {jpName:"ほうおう座", enName:"Phoenix", description:"フェニックス ― ほうおう座α星", threeCodeName:"Phe", fourCodeName:"Phoe"},
  {jpName:"がか座", enName:"Pictor", description:"画架 ― がか座α星", threeCodeName:"Pic", fourCodeName:"Pict"},
  {jpName:"うお座", enName:"Pisces", description:"魚 ― うお座η星", threeCodeName:"Psc", fourCodeName:"Pisc"},
  {jpName:"みなみのうお座", enName:"Piscis Austrinus", description:"南の魚 ― フォーマルハウト", threeCodeName:"PsA", fourCodeName:"PscA"},
  {jpName:"とも座", enName:"Puppis", description:"船尾 ― とも座ζ星", threeCodeName:"Pup", fourCodeName:"Pupp"},
  {jpName:"らしんばん座", enName:"Pyxis", description:"羅針盤 ― らしんばん座α星", threeCodeName:"Pyx", fourCodeName:"Pyxi"},
  {jpName:"レチクル座", enName:"Reticulum", description:"接眼レンズに張る線 ― レチクル座α星", threeCodeName:"Ret", fourCodeName:"Reti"},
  {jpName:"や座", enName:"Sagitta", description:"矢 ― や座γ星", threeCodeName:"Sge", fourCodeName:"Sgte"},
  {jpName:"いて座", enName:"Sagittarius", description:"射手 ― いて座ε星", threeCodeName:"Sgr", fourCodeName:"Sgtr"},
  {jpName:"さそり座", enName:"Scorpius", description:"サソリ ― アンタレス", threeCodeName:"Sco", fourCodeName:"Scor"},
  {jpName:"ちょうこくしつ座", enName:"Sculptor", description:"彫刻室 ― ちょうこくしつ座α星", threeCodeName:"Scl", fourCodeName:"Scul"},
  {jpName:"たて座", enName:"Scutum", description:"ソビェスキの盾 ― たて座α星", threeCodeName:"Sct", fourCodeName:"Scut"},
  {jpName:"へび座", enName:"Serpens", description:"ヘビ ― へび座α星", threeCodeName:"Ser", fourCodeName:"Serp"},
  {jpName:"ろくぶんぎ座", enName:"Sextans", description:"六分儀 ― ろくぶんぎ座α星", threeCodeName:"Sex", fourCodeName:"Sext"},
  {jpName:"おうし座", enName:"Taurus", description:"牡ウシ ― アルデバラン", threeCodeName:"Tau", fourCodeName:"Taur"},
  {jpName:"ぼうえんきょう座", enName:"Telescopium", description:"望遠鏡 ― ぼうえんきょう座α星", threeCodeName:"Tel", fourCodeName:"Tele"},
  {jpName:"さんかく座", enName:"Triangulum", description:"三角形 ― さんかく座β星", threeCodeName:"Tri", fourCodeName:"Tria"},
  {jpName:"みなみのさんかく座", enName:"Triangulum Australe", description:"南の三角形 ― みなみのさんかく座α星", threeCodeName:"TrA", fourCodeName:"TrAu"},
  {jpName:"きょしちょう座", enName:"Tucana", description:"オオハシ ― きょしちょう座α星", threeCodeName:"Tuc", fourCodeName:"Tucn"},
  {jpName:"おおぐま座", enName:"Ursa Major", description:"大きいクマ ― おおぐま座ε星", threeCodeName:"UMa", fourCodeName:"UMaj"},
  {jpName:"こぐま座", enName:"Ursa Minor", description:"小さいクマ ― ポラリス", threeCodeName:"UMi", fourCodeName:"UMin"},
  {jpName:"ほ座", enName:"Vela", description:"帆 ― ほ座γ星", threeCodeName:"Vel", fourCodeName:"Velr"},
  {jpName:"おとめ座", enName:"Virgo", description:"処女 ― スピカ", threeCodeName:"Vir", fourCodeName:"Virg"},
  {jpName:"とびうお座", enName:"Volans", description:"トビウオ ― とびうお座γ星", threeCodeName:"Vol", fourCodeName:"Voln"},
  {jpName:"こぎつね座", enName:"Vulpecula", description:"キツネ ― こぎつね座α星", threeCodeName:"Vul", fourCodeName:"Vulp"},
];