const FLOWER_LIST = [
  {JpName:"アイビー / アヤメ", EnName:"Ivy", Description:"「friendship（友情）」「fidelity（忠実、貞節）」「marriage（結婚）」「wedded love（夫婦愛）」"},
  {JpName:"アイリス", EnName:"Iris", Description:"「message（伝言、メッセージ）」「hope（希望）」「faith（信頼）」「friendship（友情）」「wisdom（知恵、賢さ）」"},
  {JpName:"アガパンサス", EnName:"Agapanthus", Description:"「love letter（ラブレター）」"},
  {JpName:"アカンサス", EnName:"Acanthus", Description:"「art（芸術）」「artifice（技巧）」"},
  {JpName:"アキノキリンソウ", EnName:"Goldenrod", Description:"「precaution（予防、用心、警戒）」「encouragement（励まし）」"},
  {JpName:"アサガオ", EnName:"Morning glory", Description:"「love in vain（はかない恋）」「affection（愛情）」"},
  {JpName:"アザミ", EnName:"Thistle", Description:"「independence（独立）」「nobility of character（人格の高潔さ）」「austerity（厳格）」「misanthropy（人間嫌い）」"},
  {JpName:"アザレア/ツツジ", EnName:"Azalea", Description:"「temperance（節制、禁酒）」「take care of yourself for me（私のためにお体を大切に）」「fragility（もろさ、はかなさ）」"},
  {JpName:"アジサイ", EnName:"Hydrangea", Description:"「heartlessness（冷酷）」「boastfulness（高慢）」「You are cold（あなたは冷たい人）」"},
  {JpName:"アスター / エゾギク", EnName:"China aster", Description:"「variety（多様性、変化）」「fidelity（忠実、貞節）」「I will think of you（私はあなたを想うでしょう）」"},
  {JpName:"アネモネ", EnName:"Anemone", Description:"「anticipation（期待）」「forsaken（見捨てられる、見放される）」"},
  {JpName:"アマリリス", EnName:"Amaryllis", Description:"「pride（誇り）」「splendid beauty（輝くばかりの美しさ）」"},
  {JpName:"アリウム", EnName:"Allium", Description:"「prosperity（繁栄）」「good fortune（幸運）」「humility（謙遜）」"},
  {JpName:"アルストロメリア", EnName:"Alstroemeria", Description:"「friendship（友情）」「devotion（献身的な愛）」"},
  {JpName:"アルメリア", EnName:"Thrift", Description:"「sympathy（同情、思いやり、共感）」"},
  {JpName:"アロエ", EnName:"Aloe", Description:"「bitterness（苦痛）」「grief（悲嘆）」"},
  {JpName:"アンスリウム", EnName:"Anthurium", Description:"「hospitality（温かいもてなし）」"},
  {JpName:"アンズ", EnName:"Apricot blossom", Description:"「timid love（臆病な愛）」「doubt（疑い）」「distrust（疑惑）」"},
  {JpName:"イチゴ", EnName:"Strawberry", Description:"「esteem and love（尊重と愛情）」「perfect goodness（完全なる善）」"},
  {JpName:"イヌサフラン / コルチカム", EnName:"Meadow saffron", Description:"「My best days are past（私の最良の日々は過ぎ去った）」"},
  {JpName:"イベリス", EnName:"Candytuft", Description:"「indifference（無関心）」"},
  {JpName:"ウメ", EnName:"Plum blossom", Description:"「Keep your promise（約束を守る）」「fidelity（忠実）」「beauty and longevity（美と長寿）」"},
  {JpName:"エーデルワイス", EnName:"Edelweiss", Description:"「noble courage（高潔な勇気）」「daring（大胆不敵）」"},
  {JpName:"エニシダ", EnName:"Broom", Description:"「humility（謙遜、卑下）」「neatness（清潔）」"},
  {JpName:"エリカ", EnName:"Heath", Description:"「solitude（孤独）」"},
  {JpName:"オジギソウ", EnName:"Sensitive plant", Description:"「delicate feelings（繊細な感情）」「sensitiveness（感受性、鋭敏）」"},
  {JpName:"オシロイバナ", EnName:"Marvel of Peru", Description:"「timidity（臆病）」"},
  {JpName:"オダマキ", EnName:"Columbine", Description:"「folly（愚か）」"},
  {JpName:"オトギリソウ", EnName:"St. John’s wort", Description:"「superstition（迷信）」「animosity（敵意）」"},
  {JpName:"オーニソガラム", EnName:"Star of Bethlehem", Description:"「purity（純粋）」「reconciliation（和解）」「hope（希望）」"},
  {JpName:"オリーブ", EnName:"Olive", Description:"「peace（平和）」「wisdom（知恵、賢さ）」"},
  {JpName:"オレンジ", EnName:"Orange", Description:"「purity（純粋）」「Your purity equals your loveliness（あなたの純粋さはあなたの愛らしさと釣り合っている）」"},
  {JpName:"カエデ / モミジ", EnName:"Maple", Description:"「reserve（蓄え、遠慮）」"},
  {JpName:"カスミソウ", EnName:"Baby’s breath", Description:"「everlasting love（永遠の愛）」「purity of heart（清らかな心）」「innocence（純潔）」"},
  {JpName:"カタバミ", EnName:"Wood sorrel", Description:"「joy（喜び）」「maternal tenderness（母のやさしさ）」"},
  {JpName:"カトレア", EnName:"Cattleya", Description:"「mature charm（成熟した大人の魅力）」"},
  {JpName:"カーネーション", EnName:"Carnation", Description:"「fascination（魅惑、魅力）」「love（愛情）」「distinction（卓越、名声）」"},
  {JpName:"ガーベラ", EnName:"Gerbera", Description:"「cheerfulness（上機嫌、元気）」「beauty（美）」"},
  {JpName:"カモミール", EnName:"Chamomile", Description:"「patience in adversity（逆境に耐える）」「energy in adversity（逆境で生まれる力）」"},
  {JpName:"カラー", EnName:"Calla lily", Description:"「magnificent beauty（華麗なる美）」「feminine modesty（女性のしとやかさ）」"},
  {JpName:"カランコエ", EnName:"Kalanchoe", Description:"「popularity（人気、人望）」"},
  {JpName:"カルミア", EnName:"Mountain laurel", Description:"「ambition（大望、野心）」「treachery（裏切り）」"},
  {JpName:"カンナ", EnName:"Canna", Description:"「paranoia（妄想）」「suspicion（疑い）」"},
  {JpName:"カンパニュラ", EnName:"Canterbury bells", Description:"「gratitude（感謝）」「constancy（不変、節操）」"},
  {JpName:"キキョウ", EnName:"Balloon flower", Description:"「endless love（永遠の愛）」「honesty（正直、誠実）」「the return of a friend is desired（友の帰りを願う）」「obedience（従順）」"},
  {JpName:"キク", EnName:"Chrysanthemum", Description:"「cheerfulness（上機嫌、元気）」「You’re a wonderful friend（あなたはとても素晴らしい友達）」"},
  {JpName:"キョウチクトウ", EnName:"Oleander", Description:"「caution（用心）」「beware（注意する、用心する）」"},
  {JpName:"キンギョソウ", EnName:"Snapdragon", Description:"「graciousness（上品さ、優雅さ）」「deception（ごまかし）」"},
  {JpName:"キンセンカ", EnName:"Calendula", Description:"「grief（悲嘆）」「despair（絶望）」「sorrow（悲しみ、悲哀）」"},
  {JpName:"クチナシ", EnName:"Cape jasmine", Description:"「I’m too happy（私はとても幸せです）」「transport of joy（喜びを運ぶ）」"},
  {JpName:"グラジオラス", EnName:"Gladiolus", Description:"「strength of character（人格的強さ）」「sincerity（誠実）」「preparedness（準備）」「remembrance（記憶）」"},
  {JpName:"クリスマスローズ", EnName:"Christmas rose", Description:"「relieve my anxiety（私の不安をやわらげて）」"},
  {JpName:"クレマチス", EnName:"Clematis", Description:"「mental beauty（精神の美）」「ingenuity（創意工夫）」「artifice（策略）」"},
  {JpName:"クロッカス", EnName:"Crocus", Description:"「youthful gladness（青春の喜び）」「cheerfulness（上機嫌、元気）」"},
  {JpName:"クローバー", EnName:"Clover", Description:"「think of me（私を思って）」"},
  {JpName:"ケイトウ", EnName:"Cockscomb", Description:"「foppery（〔男の〕おしゃれ）」「affectation（気取り）」「singularity（風変わり）」"},
  {JpName:"ゲッケイジュ", EnName:"Laurel", Description:"「glory（栄光）」「victory（勝利）」"},
  {JpName:"コスモス", EnName:"Cosmos", Description:"「harmony（調和）」「peace（平和）」「modesty（謙虚）」「the joys that love and life can bring（愛や人生がもたらす喜び）」「beautiful（美しい）」"},
  {JpName:"コチョウラン", EnName:"Phalaenopsis", Description:"「love（愛情）」「beauty（美）」「luxury（高級、豪華さ）」「refinement（上品、優雅）」"},
  {JpName:"ゴボウ", EnName:"Burdock", Description:"「touch me not（私にさわらないで）」「importunity（しつこくせがむ）」"},
  {JpName:"サイネリア / シネラリア", EnName:"Cineraria", Description:"「always delightful（いつも愉快）」"},
  {JpName:"サクラ", EnName:"Cherry blossom", Description:"「spiritual beauty（精神の美）」「a good education（優れた教育）」"},
  {JpName:"ザクロ", EnName:"Pomegranate", Description:"「mature elegance（円熟した優雅さ）」"},
  {JpName:"サフラン", EnName:"Saffron crocus", Description:"「mirth（歓喜）」「beware of excess（過度をつつしめ）」「Do not abuse（濫用するな）」"},
  {JpName:"サボテン", EnName:"Cactus", Description:"「endurance（忍耐）」「ardent love（燃えるような愛）」「grandeur（雄大、偉大）」「warmth（優しさ、暖かさ）」"},
  {JpName:"サルビア", EnName:"Sage", Description:"「esteem（尊敬、尊重）」「wisdom（知恵、賢さ）」「domestic virtue（家庭の徳）」"},
  {JpName:"サンザシ", EnName:"Hawthorn", Description:"「hope（希望）」"},
  {JpName:"シオン", EnName:"Aster", Description:"「patience（忍耐）」「daintiness（優美、繊細）」「symbol of love（愛の象徴）」"},
  {JpName:"ジギタリス", EnName:"Foxglove", Description:"「insincerity（不誠実）」"},
  {JpName:"シクラメン", EnName:"Cyclamen", Description:"「timid hope（遠慮がちな期待）」「shyness（内気、はにかみ）」「resignation and good-bye（退職と別れの言葉）」"},
  {JpName:"ジニア", EnName:"Zinnia", Description:"「thoughts of absent friends（不在の友を思う）」「I mourn your absence（あなたの不在を悲しむ）」"},
  {JpName:"シャクナゲ", EnName:"Rhododendron", Description:"「danger（危険）」「caution（用心）」「beware（注意する、用心する）」"},
  {JpName:"シャクヤク", EnName:"Chinese peony", Description:"「bashfulness（恥じらい、はにかみ）」「compassion（思いやり）」"},
  {JpName:"ジャスミン", EnName:"Jasmine", Description:"「amiability（愛想のよさ）」「You are cheerful and graceful（あなたは朗らかで気品がある）」"},
  {JpName:"ジンチョウゲ", EnName:"Daphne odora", Description:"「glory（栄光）」「immortality（不死、不滅）」"},
  {JpName:"シンビジウム", EnName:"Cymbidium", Description:"「magnificence（壮麗）」「gorgeous love（華やかな恋）」"},
  {JpName:"スイカズラ", EnName:"Honeysuckle", Description:"「bonds of love（愛の絆）」「devotion（献身的な愛）」"},
  {JpName:"スイセン", EnName:"Narcissus", Description:"「self-love（自己愛）」「egotism（自己中心、うぬぼれ）」「unrequited love（報われぬ恋）」"},
  {JpName:"スイートピー", EnName:"Sweet pea", Description:"「departure（門出）」「good-bye（別れの言葉）」「delicate pleasure（ほのかな喜び）」「tender memory（優しい思い出）」「blissful pleasure（至福の喜び）」"},
  {JpName:"スイレン", EnName:"Water lily", Description:"「purity of heart（清らかな心）」"},
  {JpName:"スカビオサ", EnName:"Scabiosa", Description:"「unfortunate love（不幸な愛）」「I have lost all（私はすべてを失った）」"},
  {JpName:"プラタナス", EnName:"Sycamore", Description:"「genius（天才）」「curiosity（好奇心）」"},
  {JpName:"スズラン", EnName:"Lily of the valley", Description:"「return of happiness（再び幸せが訪れる）」「sweetness（優しさ、愛らしさ）」「humility（謙遜）」「purity（純粋）」"},
  {JpName:"スターチス", EnName:"Statice", Description:"「remembrance（記憶）」「success（成功）」「sympathy（同情）」"},
  {JpName:"ストック", EnName:"Stock", Description:"「lasting beauty（永遠の美）」「bonds of affection（愛情の絆）」「contentment（満足）」「promptness（迅速さ）」"},
  {JpName:"ストレリチア", EnName:"Bird of Paradise", Description:"「magnificence（壮麗）」「faithfulness（誠実）」"},
  {JpName:"スノードロップ", EnName:"Snowdrop", Description:"「hope（希望）」「consolation（慰め）」"},
  {JpName:"スミレ", EnName:"Violet", Description:"「modesty（謙虚）」「faithfulness（誠実）」"},
  {JpName:"ゼフィランサス", EnName:"Zephyr flower", Description:"「expectation（期待）」"},
  {JpName:"ゼラニウム", EnName:"Geranium", Description:"「true friendship（真の友情）」「stupidity（愚かさ）」「gentility（育ちの良さ、上流気取り）」"},
  {JpName:"センニチコウ", EnName:"Globe amaranth", Description:"「unfading love（色あせぬ愛）」「immortality（不死、不滅）」"},
  {JpName:"タイム", EnName:"Thyme", Description:"「activity（活動、活発）」「courage（勇気）」「strength（強さ）」"},
  {JpName:"タケ", EnName:"Bamboo", Description:"「loyalty（忠誠、忠義）」「strength（強さ）」「steadfastness（不動）」"},
  {JpName:"タチアオイ", EnName:"Hollyhock", Description:"「ambition（大望、野心）」「fruitfulness（豊かな実り）」"},
  {JpName:"ダリア", EnName:"Dahlia", Description:"「dignity（威厳）」「elegance（優雅）」"},
  {JpName:"タンジー", EnName:"Tansy", Description:"「I declare war against you（あなたとの戦いを宣言する）」「resistance（抵抗）」"},
  {JpName:"タンポポ", EnName:"Dandelion", Description:"「love’s oracle（愛の神託）」「oracle（神託）」「faithfulness（誠実）」「happiness（幸福）」"},
  {JpName:"チューベローズ", EnName:"Tuberose", Description:"「dangerous pleasure（危険な快楽）」「voluptuousness（官能的）」"},
  {JpName:"チューリップ", EnName:"Tulip", Description:"「perfect lover（理想の恋人）」「fame（名声）」"},
  {JpName:"ツキミソウ / マツヨイグサ", EnName:"Evening primrose", Description:"「mute devotion（無言の愛情）」「inconstancy（移り気）」"},
  {JpName:"ツバキ", EnName:"Camellia", Description:"「admiration（敬愛、感嘆）」「perfection（完全、完璧）」"},
  {JpName:"デイジー", EnName:"Daisy", Description:"「innocence（純潔）」「beauty（美）」"},
  {JpName:"デルフィニウム", EnName:"Delphinium", Description:"「big-hearted（寛大）」「fun（楽しみ）」「ardent attachment（激しい愛着）」"},
  {JpName:"デンドロビウム", EnName:"Dendrobium", Description:"「selfish beauty（わがままな美人）」"},
  {JpName:"トケイソウ", EnName:"Passion flower", Description:"「holy love（聖なる愛）」「faith（信頼、信仰）」「religious fervour（宗教的熱情）」"},
  {JpName:"トリカブト", EnName:"Monkshood", Description:"「chivalry（騎士道）」「knight-errantry（武者修行）」"},
  {JpName:"トルコキキョウ", EnName:"Lisianthus", Description:"「appreciation（感謝）」「calming（穏やか）」"},
  {JpName:"ナシ", EnName:"Pear", Description:"「affection（愛情）」"},
  {JpName:"ナスタチウム", EnName:"Nasturtium", Description:"「patriotism（愛国心）」「victory in battle（戦いに勝つ）」"},
  {JpName:"ナズナ", EnName:"Shepherd’s purse", Description:"「I offer you my all（あなたに私のすべてを捧げます）」"},
  {JpName:"ナデシコ", EnName:"Pink", Description:"「boldness（大胆）」"},
  {JpName:"ナナカマド", EnName:"Mountain Ash", Description:"「prudence（慎重、賢明）」「I watch over you（私はあなたを見守る）」"},
  {JpName:"ニゲラ", EnName:"Nigella", Description:"「perplexity（当惑）」"},
  {JpName:"ネモフィラ", EnName:"Baby blue eyes", Description:"「success everywhere（どこでも成功）」"},
  {JpName:"ノウゼンカズラ", EnName:"Trumpet vine", Description:"「fame（名声）」"},
  {JpName:"ノコギリソウ", EnName:"Yarrow", Description:"「war（戦い）」"},
  {JpName:"パイナップル", EnName:"Pineapple", Description:"「You are perfect（あなたは完全です）」「welcome（歓迎）」"},
  {JpName:"ハイビスカス", EnName:"Hibiscus", Description:"「delicate beauty（繊細な美）」"},
  {JpName:"ハコベ", EnName:"Chickweed", Description:"「rendezvous（集合する）」"},
  {JpName:"ハス", EnName:"Lotus", Description:"「estranged love（離れゆく愛）」「eloquence（雄弁）」"},
  {JpName:"ハナズオウ", EnName:"Judas tree", Description:"「betrayal（裏切り）」「unbelief（不信仰）」"},
  {JpName:"ハナビシソウ", EnName:"California poppy", Description:"「Do not refuse me（私を拒絶しないで）」"},
  {JpName:"ハナミズキ", EnName:"Dogwood", Description:"「durability（永続性、耐久性）」「love undiminished by adversity（逆境にも耐える愛）」「Am I indifferent to you?（私があなたに関心がないとでも？）」"},
  {JpName:"バーベナ", EnName:"Verbena", Description:"「enchantment（魔力、魅力）」「sensibility（感受性）」"},
  {JpName:"バラ", EnName:"Rose", Description:"「I love you（あなたを愛してます）」「love（愛情）」「beauty（美）」「passion（情熱）」「romance（ロマンス）」"},
  {JpName:"ハルシャギク", EnName:"Coreopsis", Description:"「always cheerful（いつも陽気）」「love at first sight（一目惚れ）」"},
  {JpName:"パンジー", EnName:"Pansy", Description:"「think of me（私を思って）」「memories（思い出）」「merriment（陽気さ）」"},
  {JpName:"ヒソップ", EnName:"Hyssop", Description:"「cleanliness（清潔）」「sacrifice（犠牲）」"},
  {JpName:"ヒマワリ", EnName:"Sunflower", Description:"「adoration（愛慕、崇拝）」「false riches（偽りの富）」"},
  {JpName:"ヒヤシンス", EnName:"Hyacinth", Description:"「sports（スポーツ）」「games（ゲーム）」「rashness（無分別）」"},
  {JpName:"ヒルガオ", EnName:"Bindweed", Description:"「insinuation（ほのめかす、当てこする）」"},
  {JpName:"セイヨウヒルガオ", EnName:"Convolvulus", Description:"「bonds（絆）」"},
  {JpName:"フクシア", EnName:"Fuchsia", Description:"「humble love（つつましい愛）」「confiding love（信じる愛）」"},
  {JpName:"フクジュソウ", EnName:"Amur adonis", Description:"「sorrowful remembrance（悲しき思い出）」"},
  {JpName:"ブーゲンビリア", EnName:"Bougainvillea", Description:"「passion（情熱）」"},
  {JpName:"フジ", EnName:"Wisteria", Description:"「welcome（歓迎）」「steadfast（確固たる、しっかりした、忠実な）」"},
  {JpName:"ブドウ", EnName:"Grape", Description:"「intoxication（陶酔）」"},
  {JpName:"ブバルディア", EnName:"Bouvardia", Description:"「enthusiasm（情熱）」"},
  {JpName:"フリージア", EnName:"Freesia", Description:"「innocence（純潔）」「friendship（友情）」「trust（信頼）」"},
  {JpName:"プリムラ", EnName:"Primrose", Description:"「early youth（青春のはじめ）」「young love（青春の恋）」「I can’t live without you（あなたなしでは生きられない）」"},
  {JpName:"ブルーベル", EnName:"Bluebell", Description:"「humility（謙遜）」「constancy（不変、節操）」"},
  {JpName:"プルメリア", EnName:"Plumeria", Description:"「beauty（美）」「charm（魅力）」「grace（しとやか、上品）」"},
  {JpName:"フロックス", EnName:"Phlox", Description:"「harmony（調和）」「our souls are united（わたしたちは魂で結ばれている）」"},
  {JpName:"ベゴニア", EnName:"Begonia", Description:"「beware（注意する、用心する）」"},
  {JpName:"ペチュニア", EnName:"Petunia", Description:"「your presence soothes me（あなたと一緒なら心がやわらぐ）」"},
  {JpName:"ヘリオトロープ", EnName:"Heliotrope", Description:"「devotion（献身的な愛）」"},
  {JpName:"ベロニカ", EnName:"Speedwell", Description:"「female fidelity（女性の忠節）」"},
  {JpName:"ポインセチア", EnName:"Poinsettia", Description:"「purity（清純）」「be of good cheer（元気を出しなさい）」"},
  {JpName:"ホウセンカ", EnName:"Balsam", Description:"「impatience（短気）」「ardent love（燃えるような愛）」"},
  {JpName:"ホオズキ", EnName:"Winter Cherry", Description:"「deception（ごまかし）」"},
  {JpName:"ボダイジュ", EnName:"Linden", Description:"「conjugal love（夫婦愛）」「matrimony（結婚）」"},
  {JpName:"ボタン", EnName:"Tree peony", Description:"「bashfulness（恥じらい、はにかみ）」「compassion（思いやり）」"},
  {JpName:"ポピー", EnName:"Poppy", Description:"「oblivion（忘却）」「sleep（眠り）」「imagination（想像力）」"},
  {JpName:"マーガレット", EnName:"Marguerite", Description:"「secret love（秘密の恋）」「faith（信頼）」"},
  {JpName:"マツ", EnName:"Pine", Description:"「pity（哀れみ、同情）」「hope（希望）」"},
  {JpName:"マリーゴールド", EnName:"Marigold", Description:"「jealousy（嫉妬）」「despair（絶望）」「grief（悲嘆）」"},
  {JpName:"マンサク", EnName:"Witch hazel", Description:"「a spell（呪文、魔力）」"},
  {JpName:"ミスミソウ / ユキワリソウ", EnName:"Hepatica", Description:"「confidence（信頼、自信）」"},
  {JpName:"ミモザ", EnName:"Mimosa", Description:"「secret love（秘密の恋）」「sensitivity（感受性、思いやり）」"},
  {JpName:"ミント", EnName:"Mint", Description:"「virtue（美徳、効能）」"},
  {JpName:"ムクゲ", EnName:"Rose of Sharon", Description:"「consumed by love（恋のとりこ）」「persuasion（信念、信仰）」"},
  {JpName:"ムシトリナデシコ", EnName:"Catchfly", Description:"「snare（罠）」"},
  {JpName:"ムスカリ", EnName:"Grape hyacinth", Description:"「usefulness（有用、有益）」"},
  {JpName:"ムラサキツユクサ", EnName:"Spiderwort", Description:"「esteem not love（尊敬しているが恋愛ではない）」"},
  {JpName:"モクレン", EnName:"Magnolia", Description:"「love of nature（自然への愛）」「nobility（崇高）」「perseverance（忍耐）」「dignity（威厳）」"},
  {JpName:"モモ", EnName:"Peach blossom", Description:"「I am your captive（私はあなたのとりこ）」「unequaled qualities（比類なき素質）」"},
  {JpName:"モンステラ", EnName:"Monstera", Description:"「dedication（献身）」"},
  {JpName:"ヤグルマギク", EnName:"Cornflower", Description:"「delicacy（繊細、優美）」「refinement（上品、優雅）」"},
  {JpName:"ヤドリギ", EnName:"Mistletoe", Description:"「kiss me（私にキスして）」「I surmount difficulties（私は困難に打ち克つ）」"},
  {JpName:"ヤナギ", EnName:"Willow", Description:"「freedom（自由）」「sadness（悲哀）」"},
  {JpName:"ユリ", EnName:"Lily", Description:"「purity（純粋）」「refined beauty（洗練された美）」"},
  {JpName:"ライラック", EnName:"Lilac", Description:"「pride（誇り）」「beauty（美）」"},
  {JpName:"ラナンキュラス", EnName:"Ranunculus", Description:"「radiant charm（晴れやかな魅力）」「I am dazzled by your charms（あなたの魅力に目を奪われる）」"},
  {JpName:"ラベンダー", EnName:"Lavender", Description:"「devotion（献身的な愛）」「silence（沈黙、静寂）」「distrust（疑惑）」"},
  {JpName:"ラン", EnName:"Orchid", Description:"「love（愛情）」「beauty（美）」「refinement（上品、優雅）」「beautiful lady（美しい淑女）」"},
  {JpName:"ランタナ", EnName:"Lantana", Description:"「rigor（厳格）」"},
  {JpName:"リンゴ", EnName:"Apple blossom", Description:"「preference（優先、好み）」"},
  {JpName:"リンドウ", EnName:"Gentian", Description:"「I love you best when you are sad（悲しんでいるあなたを愛する）」「loveliness（愛らしい）」「intrinsic worth（固有の価値）」"},
  {JpName:"ルドベキア", EnName:"Rudbeckia", Description:"「justice（正義、公正）」"},
  {JpName:"ルピナス", EnName:"Lupine", Description:"「imagination（想像力）」「always happy（いつも幸せ）」「voraciousness（貪欲）」"},
  {JpName:"レモン", EnName:"Lemon", Description:"「fidelity in love（誠実な愛）」「discretion（思慮分別、自由裁量）」"},
  {JpName:"レンギョウ", EnName:"Forsythia", Description:"「anticipation（期待）」"},
  {JpName:"レンゲソウ", EnName:"Chinese milk vetch", Description:"「your presence softens my pains（あなたと一緒なら苦痛がやわらぐ）」"},
  {JpName:"ロベリア", EnName:"Lobelia", Description:"「malevolence（悪意）」"},
  {JpName:"ワスレナグサ", EnName:"Forget-me-not", Description:"「true love（真実の愛）」「memories（思い出）」"},
];


const CONSTELLATION_LIST = [
  {JpName:"アンドロメダ座", EnName:"Andromeda", Description:"アンドロメダ（神話の人物） ― アンドロメダ座β星"},
  {JpName:"ポンプ座", EnName:"Antlia", Description:"真空ポンプ ― ポンプ座α星"},
  {JpName:"ふうちょう座", EnName:"Apus", Description:"極楽鳥 ― ふうちょう座α星"},
  {JpName:"みずがめ座", EnName:"Aquarius", Description:"水瓶 ― みずがめ座β星"},
  {JpName:"わし座", EnName:"Aquila", Description:"ワシ ― アルタイル"},
  {JpName:"さいだん座", EnName:"Ara", Description:"祭壇 ― さいだん座β星"},
  {JpName:"おひつじ座", EnName:"Aries", Description:"ヒツジ ― おひつじ座α星"},
  {JpName:"ぎょしゃ座", EnName:"Auriga", Description:"御者 ― カペラ"},
  {JpName:"うしかい座", EnName:"Bootes", Description:"牛飼い ― アークトゥルス"},
  {JpName:"ちょうこくぐ座", EnName:"Caelum", Description:"彫刻刀 ― ちょうこくぐ座α星"},
  {JpName:"きりん座", EnName:"Camelopardalis", Description:"キリン ― きりん座β星"},
  {JpName:"かに座", EnName:"Cancer", Description:"カニ ― かに座β星"},
  {JpName:"りょうけん座", EnName:"Canes Venatici", Description:"猟犬 ― りょうけん座α星"},
  {JpName:"おおいぬ座", EnName:"Canis Major", Description:"大きいイヌ ― シリウス"},
  {JpName:"こいぬ座", EnName:"Canis Minor", Description:"小さいイヌ ― プロキオン"},
  {JpName:"やぎ座", EnName:"Capricornus", Description:"ヤギ ― やぎ座δ星"},
  {JpName:"りゅうこつ座", EnName:"Carina", Description:"船の竜骨 ― カノープス"},
  {JpName:"カシオペヤ座", EnName:"Cassiopeia", Description:"カッシオペイア（神話の人物） ― カシオペヤ座α星"},
  {JpName:"ケンタウルス座", EnName:"Centaurus", Description:"ケンタウロス ― ケンタウルス座α星"},
  {JpName:"ケフェウス座", EnName:"Cepheus", Description:"ケーペウス（神話の人物） ― ケフェウス座α星"},
  {JpName:"くじら座", EnName:"Cetus", Description:"海の怪物（後にクジラ） ― くじら座β星"},
  {JpName:"カメレオン座", EnName:"Chamaeleon", Description:"カメレオン ― カメレオン座α星"},
  {JpName:"コンパス座", EnName:"Circinus", Description:"製図用のディバイダ ― コンパス座α星"},
  {JpName:"はと座", EnName:"Columba", Description:"ノアのハト ― はと座α星"},
  {JpName:"かみのけ座", EnName:"Coma Berenices", Description:"ベレニケ2世の髪の毛 ― かみのけ座β星"},
  {JpName:"みなみのかんむり座", EnName:"Corona Australis", Description:"南の冠 ― みなみのかんむり座α星"},
  {JpName:"かんむり座", EnName:"Corona Borealis", Description:"北の冠 ― かんむり座α星"},
  {JpName:"からす座", EnName:"Corvus", Description:"カラス ― からす座γ星"},
  {JpName:"コップ座", EnName:"Crater", Description:"杯 ― コップ座δ星"},
  {JpName:"みなみじゅうじ座", EnName:"Crux", Description:"十字 ― みなみじゅうじ座α星"},
  {JpName:"はくちょう座", EnName:"Cygnus", Description:"ハクチョウ ― デネブ"},
  {JpName:"いるか座", EnName:"Delphinus", Description:"イルカ ― いるか座β星"},
  {JpName:"かじき座", EnName:"Dorado", Description:"シイラ ― かじき座α星"},
  {JpName:"りゅう座", EnName:"Draco", Description:"竜 ― りゅう座γ星"},
  {JpName:"こうま座", EnName:"Equuleus", Description:"仔ウマ ― こうま座α星"},
  {JpName:"エリダヌス座", EnName:"Eridanus", Description:"エーリダノス川 ― アケルナル"},
  {JpName:"ろ座", EnName:"Fornax", Description:"炉 ― ろ座α星"},
  {JpName:"ふたご座", EnName:"Gemini", Description:"双子（神話の人物） ― ポルックス"},
  {JpName:"つる座", EnName:"Grus", Description:"ツル ― つる座α星"},
  {JpName:"ヘルクレス座", EnName:"Hercules", Description:"ヘーラクレース（神話の人物） ― ヘルクレス座β星"},
  {JpName:"とけい座", EnName:"Horologium", Description:"振り子時計 ― とけい座α星"},
  {JpName:"うみへび座", EnName:"Hydra", Description:"ヒュドラ（神話の生物） ― アルファルド"},
  {JpName:"みずへび座", EnName:"Hydrus", Description:"雄のウミヘビ ― みずへび座β星"},
  {JpName:"インディアン座", EnName:"Indus", Description:"インディアン ― インディアン座α星"},
  {JpName:"とかげ座", EnName:"Lacerta", Description:"トカゲ ― とかげ座α星"},
  {JpName:"しし座", EnName:"Leo", Description:"ライオン ― レグルス"},
  {JpName:"こじし座", EnName:"Leo Minor", Description:"小さいライオン ― こじし座46番星"},
  {JpName:"うさぎ座", EnName:"Lepus", Description:"ウサギ ― うさぎ座α星"},
  {JpName:"てんびん座", EnName:"Libra", Description:"天秤 ― てんびん座β星"},
  {JpName:"おおかみ座", EnName:"Lupus", Description:"オオカミ ― おおかみ座α星"},
  {JpName:"やまねこ座", EnName:"Lynx", Description:"ヤマネコ ― やまねこ座α星"},
  {JpName:"こと座", EnName:"Lyra", Description:"竪琴 ― ベガ"},
  {JpName:"テーブルさん座", EnName:"Mensa", Description:"テーブルマウンテン ― テーブルさん座α星"},
  {JpName:"けんびきょう座", EnName:"Microscopium", Description:"顕微鏡 ― けんびきょう座γ星"},
  {JpName:"いっかくじゅう座", EnName:"Monoceros", Description:"ユニコーン ― いっかくじゅう座β星"},
  {JpName:"はえ座", EnName:"Musca", Description:"ハエ ― はえ座α星"},
  {JpName:"じょうぎ座", EnName:"Norma", Description:"定規 ― じょうぎ座γ2星"},
  {JpName:"はちぶんぎ座", EnName:"Octans", Description:"八分儀 ― はちぶんぎ座ν星"},
  {JpName:"へびつかい座", EnName:"Ophiuchus", Description:"蛇使い ― へびつかい座α星"},
  {JpName:"オリオン座", EnName:"Orion", Description:"オーリーオーン（神話の人物） ― リゲル"},
  {JpName:"くじゃく座", EnName:"Pavo", Description:"クジャク ― くじゃく座α星"},
  {JpName:"ペガスス座", EnName:"Pegasus", Description:"ペーガソス（神話の生物） ― ペガスス座ε星"},
  {JpName:"ペルセウス座", EnName:"Perseus", Description:"ペルセウス（神話の人物） ― ペルセウス座α星"},
  {JpName:"ほうおう座", EnName:"Phoenix", Description:"フェニックス ― ほうおう座α星"},
  {JpName:"がか座", EnName:"Pictor", Description:"画架 ― がか座α星"},
  {JpName:"うお座", EnName:"Pisces", Description:"魚 ― うお座η星"},
  {JpName:"みなみのうお座", EnName:"Piscis Austrinus", Description:"南の魚 ― フォーマルハウト"},
  {JpName:"とも座", EnName:"Puppis", Description:"船尾 ― とも座ζ星"},
  {JpName:"らしんばん座", EnName:"Pyxis", Description:"羅針盤 ― らしんばん座α星"},
  {JpName:"レチクル座", EnName:"Reticulum", Description:"接眼レンズに張る線 ― レチクル座α星"},
  {JpName:"や座", EnName:"Sagitta", Description:"矢 ― や座γ星"},
  {JpName:"いて座", EnName:"Sagittarius", Description:"射手 ― いて座ε星"},
  {JpName:"さそり座", EnName:"Scorpius", Description:"サソリ ― アンタレス"},
  {JpName:"ちょうこくしつ座", EnName:"Sculptor", Description:"彫刻室 ― ちょうこくしつ座α星"},
  {JpName:"たて座", EnName:"Scutum", Description:"ソビェスキの盾 ― たて座α星"},
  {JpName:"へび座", EnName:"Serpens", Description:"ヘビ ― へび座α星"},
  {JpName:"ろくぶんぎ座", EnName:"Sextans", Description:"六分儀 ― ろくぶんぎ座α星"},
  {JpName:"おうし座", EnName:"Taurus", Description:"牡ウシ ― アルデバラン"},
  {JpName:"ぼうえんきょう座", EnName:"Telescopium", Description:"望遠鏡 ― ぼうえんきょう座α星"},
  {JpName:"さんかく座", EnName:"Triangulum", Description:"三角形 ― さんかく座β星"},
  {JpName:"みなみのさんかく座", EnName:"Triangulum Australe", Description:"南の三角形 ― みなみのさんかく座α星"},
  {JpName:"きょしちょう座", EnName:"Tucana", Description:"オオハシ ― きょしちょう座α星"},
  {JpName:"おおぐま座", EnName:"Ursa Major", Description:"大きいクマ ― おおぐま座ε星"},
  {JpName:"こぐま座", EnName:"Ursa Minor", Description:"小さいクマ ― ポラリス"},
  {JpName:"ほ座", EnName:"Vela", Description:"帆 ― ほ座γ星"},
  {JpName:"おとめ座", EnName:"Virgo", Description:"処女 ― スピカ"},
  {JpName:"とびうお座", EnName:"Volans", Description:"トビウオ ― とびうお座γ星"},
  {JpName:"こぎつね座", EnName:"Vulpecula", Description:"キツネ ― こぎつね座α星"},
];